import "server-only";
import { browserBackend } from "./browser-client";
import { UI_LIMITS,UiToolError,type BrowserBackend,type UiElement,type UiProject } from "./ui-tool-types";
import { auditUi } from "./ui-audit";
type Session={id:string;key:string;userId:string;conversationId:string;project:UiProject;createdAt:number;lastUsedAt:number;navigations:number;clicks:number;screenshots:number;visited:Set<string>;clicked:Set<string>;elements:Map<string,UiElement>};
const sessions=new Map<string,Session>();
export class BrowserSessionService{constructor(private readonly backend:BrowserBackend=browserBackend){}
 async get(userId:string,conversationId:string,project:UiProject){await this.expire();const key=`${userId}:${conversationId}:${project.id}`,existing=sessions.get(key);if(existing){existing.lastUsedAt=Date.now();return existing;}if(sessions.size>=UI_LIMITS.maxConcurrentSessions)throw new UiToolError("UI_BROWSER_SESSION_LIMIT","동시 browser session 한도에 도달했습니다.",true);const created=await this.backend.request<{sessionId:string}>("/v1/sessions",{projectId:project.id,baseUrl:project.baseUrl,allowedHosts:project.allowedHosts,allowedRoutePrefixes:project.allowedRoutePrefixes,blockedRoutePrefixes:project.blockedRoutePrefixes,authProfileRef:project.authProfileRef,downloads:false,clipboard:false,geolocation:false,camera:false,microphone:false,notifications:false,fileAccess:false,formInput:false,formSubmit:false,externalNavigation:false,maxSessionMs:UI_LIMITS.sessionTtlMs});if(!/^[A-Za-z0-9_-]{8,160}$/.test(created.sessionId))throw new UiToolError("UI_BROWSER_START_FAILED","browser session 식별자가 올바르지 않습니다.");const session:Session={id:created.sessionId,key,userId,conversationId,project,createdAt:Date.now(),lastUsedAt:Date.now(),navigations:0,clicks:0,screenshots:0,visited:new Set(),clicked:new Set(),elements:new Map()};sessions.set(key,session);auditUi({userId,conversationId,uiProjectId:project.id,environment:project.environment,tool:"browser_session_started",ok:true,durationMs:0,path:null});return session;}
 async closeConversation(userId:string,conversationId:string){const prefix=`${userId}:${conversationId}:`;await Promise.all([...sessions.values()].filter(item=>item.key.startsWith(prefix)).map(item=>this.close(item)));}
 async close(session:Session){sessions.delete(session.key);await this.backend.request(`/v1/sessions/${encodeURIComponent(session.id)}/close`,{}).catch(()=>undefined);auditUi({userId:session.userId,conversationId:session.conversationId,uiProjectId:session.project.id,environment:session.project.environment,tool:"browser_session_ended",ok:true,durationMs:Date.now()-session.createdAt,path:null});}
 registerElements(session:Session,elements:ReadonlyArray<UiElement>){session.elements.clear();for(const element of elements.slice(0,UI_LIMITS.maxElements))if(/^el_[A-Za-z0-9_-]{1,100}$/.test(element.ref))session.elements.set(element.ref,element);}
 requireElement(session:Session,ref:string){if(!/^el_[A-Za-z0-9_-]{1,100}$/.test(ref))throw new UiToolError("UI_ELEMENT_NOT_FOUND","화면 요소 reference가 올바르지 않습니다.");const element=session.elements.get(ref);if(!element)throw new UiToolError("UI_ELEMENT_NOT_FOUND","현재 browser session에서 화면 요소를 찾을 수 없습니다.");return element;}
 markNavigation(session:Session,path:string){if(session.navigations>=UI_LIMITS.maxNavigations||session.visited.has(path))throw new UiToolError("UI_ACTION_NOT_ALLOWED","페이지 이동 또는 동일 route 반복 제한에 도달했습니다.");session.navigations++;session.visited.add(path);session.lastUsedAt=Date.now();}
 markClick(session:Session,ref:string){if(session.clicks>=UI_LIMITS.maxClicks||session.clicked.has(ref))throw new UiToolError("UI_ACTION_NOT_ALLOWED","클릭 또는 동일 요소 반복 제한에 도달했습니다.");session.clicks++;session.clicked.add(ref);session.lastUsedAt=Date.now();}
 markScreenshot(session:Session){if(session.screenshots>=UI_LIMITS.maxScreenshots)throw new UiToolError("UI_SCREENSHOT_NOT_ALLOWED","screenshot 생성 제한에 도달했습니다.");session.screenshots++;}
 private async expire(){const expired=[...sessions.values()].filter(item=>Date.now()-item.lastUsedAt>UI_LIMITS.sessionTtlMs);await Promise.all(expired.map(item=>this.close(item)));}
}
export const browserSessions=new BrowserSessionService();
export async function closeUiSessions(userId:string,conversationId:string){await browserSessions.closeConversation(userId,conversationId);}
