import "server-only";
import { browserBackend } from "./browser-client";
import { browserSessions } from "./browser-session-service";
import { safeUiUrl,validateUiRoute } from "./ui-route-policy";
import { sanitizeUiText,safeSameOriginPath } from "./ui-result-sanitizer";
import { UI_LIMITS,UiToolError,type UiElement,type UiProject } from "./ui-tool-types";
type Context={userId:string;conversationId:string};
type BackendPage={url:string;status:number|null;title:string;redirects?:string[];authRequired?:boolean;loaded:boolean;headings?:unknown[];landmarks?:unknown[];text?:string;elements?:unknown[];alerts?:string[];loading?:boolean;emptyState?:boolean;consoleErrorCount?:number;failedNetworkCount?:number;checkedAt?:string};

export async function openUiPage(context:Context,project:UiProject,pathInput:string,waitUntil:"domcontentloaded"|"load") {const path=validateUiRoute(project,pathInput),session=await browserSessions.get(context.userId,context.conversationId,project);browserSessions.markNavigation(session,path);const page=await browserBackend.request<BackendPage>(`/v1/sessions/${encodeURIComponent(session.id)}/open`,{path,waitUntil,maxRedirects:5,maxNetworkRequests:UI_LIMITS.maxNetworkEvents,maxConsoleEvents:UI_LIMITS.maxConsoleEvents,blockThirdParty:true,blockDownloads:true,blockMutationRequests:true});return normalizePage(project,session,page,true);}
export async function inspectUiPage(context:Context,project:UiProject,scope:"main"|"page"|"dialog",includeText:boolean,includeInteractiveElements:boolean,maxElements:number){const session=await browserSessions.get(context.userId,context.conversationId,project),page=await browserBackend.request<BackendPage>(`/v1/sessions/${encodeURIComponent(session.id)}/inspect`,{scope,includeText,includeInteractiveElements,maxElements:Math.min(maxElements,UI_LIMITS.maxElements),accessibilityFirst:true,includeHidden:false,includePasswordValues:false,includeHiddenInputs:false});return normalizePage(project,session,page,false);}
export async function inspectUiElement(context:Context,project:UiProject,elementRef:string){const session=await browserSessions.get(context.userId,context.conversationId,project),known=browserSessions.requireElement(session,elementRef),raw=await browserBackend.request<Record<string,unknown>>(`/v1/sessions/${encodeURIComponent(session.id)}/elements/${encodeURIComponent(elementRef)}`,{includeValue:false,includeHidden:false});const element=normalizeElement({...raw,ref:elementRef},project);if(element.role!==known.role)throw new UiToolError("UI_ELEMENT_NOT_FOUND","화면 요소 상태가 변경되어 다시 inspection이 필요합니다.");browserSessions.registerElements(session,[...session.elements.values()].map(item=>item.ref===element.ref?element:item));return element;}
function normalizePage(project:UiProject,session:Awaited<ReturnType<typeof browserSessions.get>>,page:BackendPage,opened:boolean){if(!page||typeof page.url!=="string")throw new UiToolError("UI_PAGE_LOAD_FAILED","browser page 결과가 올바르지 않습니다.");const current=safeUiUrl(project,page.url),text=sanitizeUiText(typeof page.text==="string"?page.text:"",UI_LIMITS.maxTextCharacters),elements=Array.isArray(page.elements)?page.elements.slice(0,UI_LIMITS.maxElements).map(value=>normalizeElement(value,project)):[];browserSessions.registerElements(session,elements);const redirects=Array.isArray(page.redirects)?page.redirects.slice(0,5).map(value=>safeUiUrl(project,String(value)).path):[];return{uiProjectId:project.id,environment:project.environment,path:current.path,finalUrl:current.url,httpStatus:typeof page.status==="number"?page.status:null,pageTitle:sanitizeUiText(page.title??"",300).text,redirects,authRequired:Boolean(page.authRequired),loaded:Boolean(page.loaded),headings:Array.isArray(page.headings)?page.headings.slice(0,30):[],landmarks:Array.isArray(page.landmarks)?page.landmarks.slice(0,30):[],text:includeSafeText(text),elements,interactiveElementCount:elements.length,alerts:Array.isArray(page.alerts)?page.alerts.slice(0,20).map(value=>sanitizeUiText(String(value),500).text):[],loading:Boolean(page.loading),emptyState:Boolean(page.emptyState),consoleErrorCount:Number(page.consoleErrorCount??0),failedNetworkRequestCount:Number(page.failedNetworkCount??0),truncated:text.truncated||Array.isArray(page.elements)&&page.elements.length>elements.length,promptInjectionDetected:text.promptInjectionDetected,opened,checkedAt:typeof page.checkedAt==="string"?page.checkedAt:new Date().toISOString()};}
const includeSafeText=(value:ReturnType<typeof sanitizeUiText>)=>value.text;
function normalizeElement(value:unknown,project:UiProject):UiElement{if(!value||typeof value!=="object")throw new UiToolError("UI_RESULT_TOO_LARGE","UI 요소 결과가 올바르지 않습니다.");const item=value as Record<string,unknown>,ref=String(item.ref??"");if(!/^el_[A-Za-z0-9_-]{1,100}$/.test(ref))throw new UiToolError("UI_RESULT_TOO_LARGE","UI 요소 reference가 올바르지 않습니다.");const role=String(item.role??"unknown").slice(0,40),name=sanitizeUiText(String(item.name??""),300).text,href=typeof item.href==="string"?safeHref(project,item.href):null,classification=["read_only","mutation","session_change","external"].includes(String(item.actionClassification))?item.actionClassification as UiElement["actionClassification"]:"unknown";return{ref,role,name,visible:Boolean(item.visible),enabled:Boolean(item.enabled),disabled:Boolean(item.disabled),label:typeof item.label==="string"?sanitizeUiText(item.label,300).text:null,placeholder:role==="textbox"&&String(item.inputType)==="password"?null:typeof item.placeholder==="string"?sanitizeUiText(item.placeholder,300).text:null,required:Boolean(item.required),validationState:typeof item.validationState==="string"?item.validationState.slice(0,40):null,tooltip:typeof item.tooltip==="string"?sanitizeUiText(item.tooltip,300).text:null,href,actionClassification:classification,clickable:Boolean(item.clickable),position:typeof item.position==="string"?item.position.slice(0,80):null};}
function safeHref(project:UiProject,value:string){if(value.startsWith("#"))return value.slice(0,100);try{const path=value.startsWith("/")?value:safeSameOriginPath(value,new URL(project.baseUrl).origin);return path?validateUiRoute(project,path):null;}catch{return null;}}
