import "server-only";
import { browserBackend } from "./browser-client";
import { browserSessions } from "./browser-session-service";
import { assertSafeUiClick } from "./ui-action-policy";
import { safeUiUrl,validateUiRoute } from "./ui-route-policy";
import type { UiProject } from "./ui-tool-types";
type Context={userId:string;conversationId:string};
export async function clickUiElement(context:Context,project:UiProject,elementRef:string,expectedAction:string){const session=await browserSessions.get(context.userId,context.conversationId,project),element=browserSessions.requireElement(session,elementRef);assertSafeUiClick(project,element,expectedAction);browserSessions.markClick(session,elementRef);const result=await browserBackend.request<{url:string;navigation:boolean;dialogOpened:boolean;networkMutationBlocked:boolean;checkedAt?:string}>(`/v1/sessions/${encodeURIComponent(session.id)}/click`,{elementRef,expectedAction,allowFormSubmit:false,allowMutation:false,allowExternalNavigation:false});const current=safeUiUrl(project,result.url);return{uiProjectId:project.id,environment:project.environment,path:current.path,element:{role:element.role,name:element.name},expectedAction,navigation:Boolean(result.navigation),dialogOpened:Boolean(result.dialogOpened),mutationBlocked:Boolean(result.networkMutationBlocked),checkedAt:result.checkedAt??new Date().toISOString()};}
export async function navigateUiRoute(context:Context,project:UiProject,pathInput:string){const session=await browserSessions.get(context.userId,context.conversationId,project),path=validateUiRoute(project,pathInput);browserSessions.markNavigation(session,path);const result=await browserBackend.request<{url:string;status:number|null;checkedAt?:string}>(`/v1/sessions/${encodeURIComponent(session.id)}/navigate`,{path,allowExternalNavigation:false,blockMutationRequests:true,blockDownloads:true});const current=safeUiUrl(project,result.url);return{uiProjectId:project.id,environment:project.environment,path:current.path,httpStatus:result.status,checkedAt:result.checkedAt??new Date().toISOString()};}
