import "server-only";
import { UiToolError,type UiEnvironment,type UiProject } from "./ui-tool-types";
const environments=new Set<UiEnvironment>(["local","development","staging","production"]),safeId=/^[A-Za-z0-9_.-]{1,100}$/;
export function getUiProjects(env:NodeJS.ProcessEnv=process.env):ReadonlyArray<UiProject>{const raw=env.UI_PROJECTS_JSON?.trim();if(!raw)throw new UiToolError("UI_PROJECT_NOT_CONNECTED","UI 프로젝트 연결이 구성되지 않았습니다.");let values:unknown;try{values=JSON.parse(raw);}catch{throw new UiToolError("UI_PROJECT_NOT_CONNECTED","UI 프로젝트 설정 형식이 올바르지 않습니다.");}if(!Array.isArray(values))throw new UiToolError("UI_PROJECT_NOT_CONNECTED","UI 프로젝트 설정 형식이 올바르지 않습니다.");return values.map(parseProject);}
function parseProject(value:unknown):UiProject{if(!value||typeof value!=="object")throw new UiToolError("UI_PROJECT_NOT_CONNECTED","UI 프로젝트 설정을 확인해 주세요.");const item=value as Record<string,unknown>;if(!safeId.test(String(item.id))||!safeId.test(String(item.runtimeProjectId))||typeof item.displayName!=="string"||!environments.has(item.environment as UiEnvironment))throw new UiToolError("UI_PROJECT_NOT_CONNECTED","UI 프로젝트 필수 설정이 올바르지 않습니다.");const environment=item.environment as UiEnvironment,url=parseBaseUrl(item.baseUrl,environment),allowedHosts=arrayOfStrings(item.allowedHosts),allowedRoutePrefixes=arrayOfRoutes(item.allowedRoutePrefixes),blockedRoutePrefixes=arrayOfRoutes(item.blockedRoutePrefixes??[]),connectionIds=Array.isArray(item.connectionIds)?item.connectionIds.map(Number):[];if(!allowedHosts.includes(url.hostname)||!allowedRoutePrefixes.length||connectionIds.some(id=>!Number.isSafeInteger(id)||id<1))throw new UiToolError("UI_PROJECT_NOT_CONNECTED","UI 프로젝트 접근 범위 설정이 올바르지 않습니다.");const authRequired=Boolean(item.authRequired),authProfileRef=typeof item.authProfileRef==="string"&&safeId.test(item.authProfileRef)?item.authProfileRef:null;if(authRequired&&!authProfileRef)throw new UiToolError("UI_AUTH_SESSION_NOT_AVAILABLE","인증 UI용 안전한 browser profile이 없습니다.");return{id:String(item.id),runtimeProjectId:String(item.runtimeProjectId),displayName:item.displayName.slice(0,160),environment,baseUrl:url.origin,allowedHosts,allowedRoutePrefixes,blockedRoutePrefixes,connectionIds:[...new Set(connectionIds)],authRequired,authProfileRef,allowClicks:Boolean(item.allowClicks),allowScreenshots:Boolean(item.allowScreenshots),allowNetwork:item.allowNetwork!==false,allowConsole:item.allowConsole!==false,active:item.active!==false};}
function parseBaseUrl(value:unknown,environment:UiEnvironment){if(typeof value!=="string")throw new UiToolError("UI_PROJECT_NOT_CONNECTED","UI base URL이 없습니다.");try{const url=new URL(value),local=environment==="local"&&(url.hostname==="127.0.0.1"||url.hostname==="localhost");if((url.protocol!=="https:"&&!local)||url.username||url.password||url.pathname!=="/"||url.search||url.hash)throw new Error();return url;}catch{throw new UiToolError("UI_PROJECT_NOT_CONNECTED","UI base URL 설정이 안전하지 않습니다.");}}
const arrayOfStrings=(value:unknown)=>Array.isArray(value)?[...new Set(value.filter((item):item is string=>typeof item==="string"&&/^[A-Za-z0-9.-]{1,253}$/.test(item)).map(item=>item.toLowerCase()))]:[];
const arrayOfRoutes=(value:unknown)=>Array.isArray(value)?[...new Set(value.filter((item):item is string=>typeof item==="string"&&item.startsWith("/")&&!item.includes("..")&&!item.includes("://")))]:[];
export function requireUiProject(projectId:string,connectionId:number|null,projects=getUiProjects()){const project=projects.find(item=>item.id===projectId&&item.active);if(!project)throw new UiToolError("UI_PROJECT_NOT_FOUND","UI 프로젝트를 찾을 수 없습니다.");if(!connectionId||!project.connectionIds.includes(connectionId))throw new UiToolError("UI_PROJECT_ACCESS_DENIED","현재 DB connection에 연결된 UI 프로젝트가 아닙니다.");return project;}
export function selectUiProject(environment:UiEnvironment,connectionId:number|null,projects=getUiProjects()){const matches=projects.filter(item=>item.active&&item.environment===environment&&connectionId&&item.connectionIds.includes(connectionId));if(matches.length!==1)throw new UiToolError(matches.length?"UI_PROJECT_ACCESS_DENIED":"UI_PROJECT_NOT_CONNECTED",matches.length?"UI 프로젝트를 하나로 결정할 수 없습니다.":"현재 connection과 environment에 연결된 UI 프로젝트가 없습니다.");return matches[0];}
export function publicUiProject(project:UiProject,browserAvailable:boolean){const host=new URL(project.baseUrl).hostname;return{uiProjectId:project.id,displayName:project.displayName,runtimeProjectId:project.runtimeProjectId,environment:project.environment,baseHost:host,publicRoutes:project.allowedRoutePrefixes,authenticatedInspection:project.authRequired&&Boolean(project.authProfileRef)&&browserAvailable,screenshotSupported:browserAvailable&&project.allowScreenshots,clickSupported:browserAvailable&&project.allowClicks,networkInspection:browserAvailable&&project.allowNetwork,consoleInspection:browserAvailable&&project.allowConsole,checkedAt:new Date().toISOString()};}
