import "server-only";
import type { RowDataPacket } from "mysql2/promise";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { tableFileName, writeVersionedSchemaFiles } from "./write-schema-files";
import { calculateSchemaHash } from "./schema-hash";
import { publishCurrentSchema } from "./schema-current";
import type { ForeignKeySchema, IndexSchema, SchemaBundle, SchemaCurrentPointer, TableSchema } from "./types";
import { createTargetPool, type TargetConnection } from "../db/target-connections";

const iso=(value:unknown)=>value?new Date(value as string|number|Date).toISOString():null;
export async function collectMysqlSchema(c:TargetConnection){
 const pool=createTargetPool(c),generatedAt=new Date().toISOString();
 try{
  const params=[c.databaseName];
  const [[tables],[columns],[keys],[constraints],[statistics],[views]]=await Promise.all([
   pool.query<RowDataPacket[]>(`SELECT TABLE_NAME,TABLE_TYPE,TABLE_COMMENT,ENGINE,TABLE_COLLATION,TABLE_ROWS,CREATE_TIME,UPDATE_TIME FROM information_schema.TABLES WHERE TABLE_SCHEMA=? ORDER BY TABLE_NAME`,params),
   pool.query<RowDataPacket[]>(`SELECT TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION,DATA_TYPE,COLUMN_TYPE,CHARACTER_MAXIMUM_LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE,DATETIME_PRECISION,IS_NULLABLE,COLUMN_DEFAULT,EXTRA,GENERATION_EXPRESSION,CHARACTER_SET_NAME,COLLATION_NAME,COLUMN_COMMENT,COLUMN_KEY FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=? ORDER BY TABLE_NAME,ORDINAL_POSITION`,params),
   pool.query<RowDataPacket[]>(`SELECT TABLE_NAME,CONSTRAINT_NAME,COLUMN_NAME,ORDINAL_POSITION,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA=? AND REFERENCED_TABLE_NAME IS NOT NULL ORDER BY TABLE_NAME,CONSTRAINT_NAME,ORDINAL_POSITION`,params),
   pool.query<RowDataPacket[]>(`SELECT TABLE_NAME,CONSTRAINT_NAME,UPDATE_RULE,DELETE_RULE FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=?`,params),
   pool.query<RowDataPacket[]>(`SELECT TABLE_NAME,INDEX_NAME,NON_UNIQUE,INDEX_TYPE,SEQ_IN_INDEX,COLUMN_NAME,SUB_PART,COLLATION FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=? ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX`,params),
   pool.query<RowDataPacket[]>(`SELECT TABLE_NAME,CHECK_OPTION,IS_UPDATABLE,SECURITY_TYPE,VIEW_DEFINITION FROM information_schema.VIEWS WHERE TABLE_SCHEMA=?`,params),
  ]);
  const relationships:ForeignKeySchema[]=[];
  for(const row of keys){if(relationships.some(item=>item.sourceTable===row.TABLE_NAME&&item.constraintName===row.CONSTRAINT_NAME))continue;const parts=keys.filter(item=>item.TABLE_NAME===row.TABLE_NAME&&item.CONSTRAINT_NAME===row.CONSTRAINT_NAME),rule=constraints.find(item=>item.TABLE_NAME===row.TABLE_NAME&&item.CONSTRAINT_NAME===row.CONSTRAINT_NAME);relationships.push({constraintName:String(row.CONSTRAINT_NAME),sourceTable:String(row.TABLE_NAME),sourceColumns:parts.map(item=>String(item.COLUMN_NAME)),targetTable:String(row.REFERENCED_TABLE_NAME),targetColumns:parts.map(item=>String(item.REFERENCED_COLUMN_NAME)),updateRule:String(rule?.UPDATE_RULE??"UNKNOWN"),deleteRule:String(rule?.DELETE_RULE??"UNKNOWN")});}
  const docs=tables.map(row=>{
   const tableName=String(row.TABLE_NAME),foreignKeys=relationships.filter(item=>item.sourceTable===tableName),indexRows=statistics.filter(item=>item.TABLE_NAME===tableName),indexes:IndexSchema[]=[];
   for(const index of indexRows){if(indexes.some(item=>item.name===index.INDEX_NAME))continue;const parts=indexRows.filter(item=>item.INDEX_NAME===index.INDEX_NAME);indexes.push({name:String(index.INDEX_NAME),primary:index.INDEX_NAME==="PRIMARY",unique:Number(index.NON_UNIQUE)===0,type:String(index.INDEX_TYPE??"UNKNOWN"),columns:parts.map(item=>({ordinalPosition:Number(item.SEQ_IN_INDEX),name:String(item.COLUMN_NAME),prefixLength:item.SUB_PART===null?null:Number(item.SUB_PART),direction:item.COLLATION==="D"?"DESC":item.COLLATION==="A"?"ASC":null}))});}
   const cs=columns.filter(item=>item.TABLE_NAME===tableName).map(item=>{const fk=keys.find(key=>key.TABLE_NAME===tableName&&key.COLUMN_NAME===item.COLUMN_NAME);return {ordinalPosition:Number(item.ORDINAL_POSITION),name:String(item.COLUMN_NAME),dataType:String(item.DATA_TYPE),columnType:String(item.COLUMN_TYPE),characterMaximumLength:item.CHARACTER_MAXIMUM_LENGTH===null?null:Number(item.CHARACTER_MAXIMUM_LENGTH),numericPrecision:item.NUMERIC_PRECISION===null?null:Number(item.NUMERIC_PRECISION),numericScale:item.NUMERIC_SCALE===null?null:Number(item.NUMERIC_SCALE),datetimePrecision:item.DATETIME_PRECISION===null?null:Number(item.DATETIME_PRECISION),nullable:item.IS_NULLABLE==="YES",defaultValue:item.COLUMN_DEFAULT===null?null:String(item.COLUMN_DEFAULT),extra:String(item.EXTRA||""),generated:Boolean(item.GENERATION_EXPRESSION),generationExpression:item.GENERATION_EXPRESSION?String(item.GENERATION_EXPRESSION):null,characterSet:item.CHARACTER_SET_NAME?String(item.CHARACTER_SET_NAME):null,collation:item.COLLATION_NAME?String(item.COLLATION_NAME):null,comment:String(item.COLUMN_COMMENT||""),primaryKey:item.COLUMN_KEY==="PRI",uniqueIndex:item.COLUMN_KEY==="UNI",indexed:indexRows.some(index=>index.COLUMN_NAME===item.COLUMN_NAME),foreignKey:Boolean(fk),referencedTable:fk?String(fk.REFERENCED_TABLE_NAME):null,referencedColumn:fk?String(fk.REFERENCED_COLUMN_NAME):null};});
   const view=views.find(item=>item.TABLE_NAME===tableName),table:TableSchema={name:tableName,type:row.TABLE_TYPE,comment:String(row.TABLE_COMMENT||""),engine:row.ENGINE?String(row.ENGINE):null,characterSet:row.TABLE_COLLATION?String(row.TABLE_COLLATION).split("_")[0]:null,collation:row.TABLE_COLLATION?String(row.TABLE_COLLATION):null,estimatedRows:row.TABLE_ROWS===null?null:Number(row.TABLE_ROWS),createdAt:iso(row.CREATE_TIME),updatedAt:iso(row.UPDATE_TIME),columns:cs,primaryKey:cs.filter(item=>item.primaryKey).map(item=>item.name),foreignKeys,indexes,view:view?{checkOption:view.CHECK_OPTION?String(view.CHECK_OPTION):null,updatable:view.IS_UPDATABLE==="YES",securityType:view.SECURITY_TYPE?String(view.SECURITY_TYPE):null,definition:view.VIEW_DEFINITION?String(view.VIEW_DEFINITION):null,definitionAccessible:Boolean(view.VIEW_DEFINITION)}:null};
   return {formatVersion:1 as const,databaseName:c.databaseName,table};
  });
  const manifestTables=docs.map(document=>({name:document.table.name,type:document.table.type,comment:document.table.comment,columnCount:document.table.columns.length,primaryKey:document.table.primaryKey,foreignKeyCount:document.table.foreignKeys.length,indexCount:document.table.indexes.length,file:`tables/${tableFileName(document.table.name)}`}));
  const bundle:SchemaBundle={manifest:{formatVersion:1,connectionId:c.id,connectionKey:c.connectionKey,displayName:c.displayName,dbType:"mysql",databaseName:c.databaseName,generatedAt,tableCount:docs.filter(item=>item.table.type==="BASE TABLE").length,viewCount:docs.filter(item=>item.table.type==="VIEW").length,tables:manifestTables},relationships:{formatVersion:1,generatedAt,relationships},tables:docs};
  let versionNo=1;try{const current=JSON.parse(await readFile(path.join(process.cwd(),"schemas",c.connectionKey,"current.json"),"utf8")) as SchemaCurrentPointer;versionNo=current.latestVersion+1;}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}
  const schemaHash=calculateSchemaHash(bundle),result=await writeVersionedSchemaFiles(bundle,versionNo);await publishCurrentSchema({formatVersion:1,connectionId:c.id,connectionKey:c.connectionKey,latestVersion:versionNo,path:`versions/v${String(versionNo).padStart(6,"0")}`,generatedAt,schemaHash});return {...result,versionNo,schemaHash};
 }finally{await pool.end();}
}
