import { describe, expect, test } from "bun:test";
import { selectSchema } from "./select-schema";
import type { SchemaBundle, TableSchemaDocument } from "./types";
function table(name: string, comment: string, column: string, columnComment: string): TableSchemaDocument { return { formatVersion: 1, databaseName: "sales", table: { name, type: "BASE TABLE", comment, engine: "InnoDB", characterSet: "utf8mb4", collation: null, estimatedRows: null, createdAt: null, updatedAt: null, columns: [{ ordinalPosition: 1, name: column, dataType: "int", columnType: "int", characterMaximumLength: null, numericPrecision: 10, numericScale: 0, datetimePrecision: null, nullable: false, defaultValue: null, extra: "", generated: false, generationExpression: null, characterSet: null, collation: null, comment: columnComment, primaryKey: true, uniqueIndex: true, indexed: true, foreignKey: false, referencedTable: null, referencedColumn: null }], primaryKey: [column], foreignKeys: [], indexes: [], view: null } }; }
function bundle(): SchemaBundle { const tables = [table("orders", "주문 내역", "client_id", "거래처 식별자"), table("clients", "거래처 정보", "id", "거래처 키"), table("inventory", "재고", "item_id", "품목")]; return { manifest: { formatVersion: 1, connectionId: 1, connectionKey: "sales", displayName: "매출", dbType: "mysql", databaseName: "sales", generatedAt: "2026-01-01T00:00:00Z", tableCount: 3, viewCount: 0, tables: tables.map((item) => ({ name: item.table.name, type: "BASE TABLE", comment: item.table.comment, columnCount: 1, primaryKey: item.table.primaryKey, foreignKeyCount: 0, indexCount: 0, file: `tables/t-${Buffer.from(item.table.name).toString("hex")}.json` })) }, relationships: { formatVersion: 1, generatedAt: "2026-01-01T00:00:00Z", relationships: [{ constraintName: "fk_order_client", sourceTable: "orders", sourceColumns: ["client_id"], targetTable: "clients", targetColumns: ["id"], updateRule: "RESTRICT", deleteRule: "RESTRICT" }] }, tables }; }
describe("schema selection", () => {
  test("uses column comments and expands one FK hop", () => { const result = selectSchema("거래처별 주문", bundle()); expect(result.selectedTables).toContain("orders"); expect(result.selectedTables).toContain("clients"); expect(result.selectedTables).not.toContain("inventory"); expect(result.totalSerializedCharacters).toBeLessThanOrEqual(100_000); });
  test("rejects unrelated questions instead of sending every table", () => expect(() => selectSchema("날씨 예보", bundle())).toThrow());
});
