export const ALLOWED_PRIVILEGES = new Set(["SELECT", "SHOW VIEW", "USAGE"]);
export const DATA_CHANGE_PRIVILEGES = new Set(["INSERT", "UPDATE", "DELETE", "EXECUTE", "EVENT", "TRIGGER"]);
export const SCHEMA_CHANGE_PRIVILEGES = new Set(["CREATE", "ALTER", "DROP", "INDEX", "CREATE VIEW", "ALTER ROUTINE", "CREATE ROUTINE", "CREATE TEMPORARY TABLES", "REFERENCES", "TRIGGER"]);
export const ADMIN_PRIVILEGES = new Set(["ALL PRIVILEGES", "GRANT OPTION", "SUPER", "SYSTEM_USER", "SYSTEM_VARIABLES_ADMIN", "SESSION_VARIABLES_ADMIN", "PROCESS", "FILE", "RELOAD", "SHUTDOWN", "CREATE USER", "DROP USER", "ROLE_ADMIN", "CONNECTION_ADMIN", "REPLICATION SLAVE", "REPLICATION CLIENT", "BINLOG_ADMIN", "BINLOG_ENCRYPTION_ADMIN"]);
export const KNOWN_PRIVILEGES = new Set([...ALLOWED_PRIVILEGES, ...DATA_CHANGE_PRIVILEGES, ...SCHEMA_CHANGE_PRIVILEGES, ...ADMIN_PRIVILEGES]);
