import type { AnalysisMessage, DatabaseOption } from "./types";
type Props = Readonly<{ database: DatabaseOption | null; messages: ReadonlyArray<AnalysisMessage>; question: string; disabled: boolean; submitting: boolean; error: string | null; notice: string | null; onQuestionChange: (value: string) => void; onClear: () => void; onSubmit: () => void; onOpenHistory: () => void }>;
const riskLabel={read_only:"읽기 전용",data_change:"데이터 변경",schema_change:"스키마 변경",destructive:"파괴적 변경"} as const;
export function AssistantPanel({ database, messages, question, disabled, submitting, error, notice, onQuestionChange, onClear, onSubmit, onOpenHistory }: Props) {
 return <section className="analysis-panel assistant-panel" aria-labelledby="assistant-heading"><header className="panel-bar"><div><span>ASK</span><h2 id="assistant-heading">GPT 질문 및 답변</h2></div><div className="panel-actions"><button type="button" className="text-button" onClick={onOpenHistory} disabled={!database}>최근 질문</button><button type="button" className="text-button" onClick={onClear} disabled={!messages.length}>대화 초기화</button></div></header><div className="panel-context">{database ? `${database.displayName} 스키마 기준` : "대상 DB를 먼저 선택하세요"}</div><div className="message-list" aria-live="polite">
 {messages.length===0 ? <div className="panel-empty"><strong>조회하거나 검토할 내용을 입력하세요.</strong><p>변경 SQL은 참고 절차만 제공하며 사이트에서 실행하지 않습니다.</p></div> : messages.map(m=><article key={m.id} className={`message message--${m.role}`}><span>{m.role==="user"?"질문":m.status==="pending"?"답변 생성 중":"답변"}</span><p>{m.content}</p>{m.riskLevel&&<strong className={`risk-badge risk-badge--${m.riskLevel}`}>위험도: {riskLabel[m.riskLevel]}</strong>}{m.requestType==="ddl_dml_reference"&&<small className="message-warning">사이트에서 실행할 수 없는 참고용 변경 SQL입니다.</small>}{m.transactionGuidance?.summary&&<section className="guidance-section"><b>트랜잭션 안내</b><p>{m.transactionGuidance.summary}</p></section>}{m.executionPlan&&<div className="execution-plan"><Plan title="실행 전 점검" items={m.executionPlan.preChecks}/><Plan title="변경 SQL" items={m.executionPlan.statements}/><Plan title="실행 후 검증" items={m.executionPlan.postChecks}/><Plan title="ROLLBACK 또는 복구" items={m.executionPlan.rollbackOrRecovery}/></div>}{m.referencedTables?.length?<small>참조: {m.referencedTables.join(", ")}</small>:null}{m.assumptions?.map(x=><small key={`a-${x}`}>가정: {x}</small>)}{m.warnings?.map(x=><small className="message-warning" key={`w-${x}`}>주의: {x}</small>)}{m.sqlApplied&&<small>SQL 편집기에 반영됨</small>}</article>)}
 </div>{notice&&<p className="workspace-notice" role="status">{notice}</p>}<div className="question-compose"><label htmlFor="analysis-question">업무 요청</label><textarea id="analysis-question" value={question} onChange={e=>onQuestionChange(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&e.ctrlKey){e.preventDefault();onSubmit();}}} placeholder="예: 지난달 거래처별 주문 금액을 보고 싶습니다." disabled={disabled||submitting}/>{error&&<p className="compose-error" role="alert">{error}</p>}<div><small>Enter 줄바꿈 · Ctrl+Enter 전송</small><button type="button" onClick={onSubmit} disabled={disabled||submitting||question.trim().length<2}>{submitting?"생성 중…":"질문 전송"}</button></div></div></section>;
}
function Plan({title,items}:{title:string;items:ReadonlyArray<string>}){return <section><b>{title}</b>{items.map((x,i)=><pre key={`${title}-${i}`}>{x}</pre>)}</section>}
