import {describe,expect,test} from "bun:test";
import {parseReadonlySql} from "./readonly-sql-parser";
import {sanitizeSqlRows} from "./sql-result-sanitizer";
import {validateReadonlySql} from "./readonly-sql-validator";
import type {TargetConnection} from "@/lib/server/db/target-connections";
import type {SchemaBundle,TableSchema} from "@/lib/server/schema/types";
const connection={id:1,connectionKey:"sales",displayName:"Sales",host:"localhost",port:3306,databaseName:"sales",username:"reader",encryptedPassword:"x",active:true,createdAt:new Date(),checkedAt:null,connectionStatus:"healthy"} satisfies TargetConnection;
const table={name:"orders",type:"BASE TABLE",comment:"",engine:"InnoDB",characterSet:null,collation:null,estimatedRows:10,createdAt:null,updatedAt:null,columns:["id","customer_id","created_at","email","password_hash"].map((name,index)=>({ordinalPosition:index+1,name,dataType:"varchar",columnType:"varchar(10)",characterMaximumLength:10,numericPrecision:null,numericScale:null,datetimePrecision:null,nullable:true,defaultValue:null,extra:"",generated:false,generationExpression:null,characterSet:null,collation:null,comment:"",primaryKey:name==="id",uniqueIndex:false,indexed:name==="id",foreignKey:false,referencedTable:null,referencedColumn:null})),primaryKey:["id"],foreignKeys:[],indexes:[],view:null} satisfies TableSchema;
const bundle={manifest:{formatVersion:1,connectionId:1,connectionKey:"sales",displayName:"Sales",dbType:"mysql",databaseName:"sales",generatedAt:new Date(0).toISOString(),tableCount:1,viewCount:0,tables:[{name:"orders",type:"BASE TABLE",comment:"",columnCount:5,primaryKey:["id"],foreignKeyCount:0,indexCount:0,file:"orders.json"}]},relationships:{formatVersion:1,generatedAt:new Date(0).toISOString(),relationships:[]},tables:[{formatVersion:1,databaseName:"sales",table}]} satisfies SchemaBundle;
describe("readonly SQL parser and policy",()=>{
 test("distinguishes literal semicolons and extracts CTE/JOIN aliases",()=>{const parsed=parseReadonlySql("WITH recent AS (SELECT id FROM orders) SELECT o.id, ';' AS mark FROM orders o JOIN recent r ON r.id=o.id LIMIT 10;");expect(parsed.tokens.filter(t=>t.kind==="symbol"&&t.value===";")).toHaveLength(1);expect(parsed.tables).toEqual(["orders"]);expect(parsed.aliases.get("o")).toBe("orders");expect(parsed.joinCount).toBe(1);});
 test("allows schema-backed SELECT and applies a wrapper limit",async()=>{const result=await validateReadonlySql("SELECT o.id FROM orders o",connection,20,undefined,bundle);expect(result.valid).toBeTrue();expect(result.executionSql).toContain("tq_readonly_result LIMIT 21");expect(result.referencedColumns).toEqual(["orders.id"]);});
 test.each([["INSERT INTO orders(id) VALUES(1)","SQL_NOT_READONLY"],["SELECT * FROM orders; SELECT * FROM orders","SQL_MULTIPLE_STATEMENTS"],["SELECT SLEEP(5) FROM orders","SQL_FORBIDDEN_FUNCTION"],["SELECT * FROM mysql.user","SQL_SYSTEM_SCHEMA_ACCESS_DENIED"],["SELECT o.missing FROM orders o","SQL_COLUMN_NOT_FOUND"]] as const)("blocks %s",async(sql,code)=>{const result=await validateReadonlySql(sql,connection,20,undefined,bundle);expect(result.valid).toBeFalse();expect(result.errors.map(e=>e.code)).toContain(code);});
 test("does not treat forbidden words inside strings as syntax",async()=>{expect((await validateReadonlySql("SELECT 'DELETE' AS label FROM orders LIMIT 1",connection,20,undefined,bundle)).valid).toBeTrue();});
});
test("masks personal data and blocks explicit secrets",()=>{const result=sanitizeSqlRows([{id:1,email:"a@example.com",password_hash:"hash",amount:BigInt(10),created_at:new Date("2026-01-01T00:00:00Z")}]);expect(result.rows[0]).toMatchObject({email:"[MASKED]",password_hash:"[BLOCKED]",amount:"10",created_at:"2026-01-01T00:00:00.000Z"});expect(result.maskedColumns).toEqual(["email"]);});
test("applies structured business sensitivity without weakening defaults",()=>{const result=sanitizeSqlRows([{nickname:"safe",customer_code:"C1",internal_note:"memo"}],new Map([["nickname","personal"],["customer_code","secret"],["internal_note","public"]]));expect(result.rows[0]).toEqual({nickname:"[MASKED]",customer_code:"[BLOCKED]",internal_note:"memo"});});
