import type { TargetConnection } from "@/lib/server/db/target-connections";
import { loadSchemaContext } from "@/lib/server/schema-tools/context-service";
import { parseReadonlySql } from "./readonly-sql-parser";
import { DEFAULT_SQL_TOOL_POLICY, type ReadonlyValidation, type SqlErrorCode, type SqlToolIssue, type SqlToolPolicy } from "./sql-tool-types";
import type { SchemaBundle } from "@/lib/server/schema/types";
const FORBIDDEN=new Set(["INSERT","UPDATE","DELETE","REPLACE","MERGE","UPSERT","CREATE","ALTER","DROP","TRUNCATE","RENAME","GRANT","REVOKE","SET","USE","CALL","EXECUTE","PREPARE","DEALLOCATE","LOAD","LOCK","UNLOCK","ANALYZE","OPTIMIZE","REPAIR","FLUSH","KILL","DO","HANDLER"]);
const BAD_FUNCTIONS=new Set(["SLEEP","BENCHMARK","LOAD_FILE","GET_LOCK","RELEASE_LOCK","IS_FREE_LOCK","MASTER_POS_WAIT"]),SYSTEM=new Set(["information_schema","mysql","performance_schema","sys"]);
const issue=(code:SqlErrorCode,message:string,retryable=false,extra?:Partial<SqlToolIssue>):SqlToolIssue=>({code,message,retryable,...extra});
export async function validateReadonlySql(sql:unknown,connection:TargetConnection,requestedMaxRows?:number,policy:SqlToolPolicy=DEFAULT_SQL_TOOL_POLICY,schemaOverride?:SchemaBundle):Promise<ReadonlyValidation>{
 const errors:SqlToolIssue[]=[],warnings:SqlToolIssue[]=[];if(typeof sql!=="string"||!sql.trim())return {valid:false,readonly:false,errors:[issue("SQL_EMPTY","SQL을 입력해 주세요.",true)],warnings:[],referencedTables:[],referencedColumns:[]};if(sql.length>policy.maxSqlLength)return {valid:false,readonly:false,errors:[issue("SQL_TOO_LONG","SQL이 최대 길이를 초과했습니다.")],warnings:[],referencedTables:[],referencedColumns:[]};
 let parsed;try{parsed=parseReadonlySql(sql);}catch{return {valid:false,readonly:false,errors:[issue("SQL_PARSE_FAILED","SQL 구조를 안전하게 해석할 수 없습니다.",true)],warnings:[],referencedTables:[],referencedColumns:[]};}
 const semis=parsed.tokens.filter(t=>t.kind==="symbol"&&t.value===";");if(semis.length>1||(semis.length===1&&semis[0]!==parsed.tokens.at(-1)))errors.push(issue("SQL_MULTIPLE_STATEMENTS","단일 statement만 허용됩니다."));
 const first=parsed.tokens[0]?.upper;if(first!=="SELECT"&&first!=="WITH")errors.push(issue("SQL_NOT_READONLY","SELECT 또는 WITH ... SELECT만 허용됩니다."));
 if(parsed.tokens.some(t=>t.kind==="word"&&FORBIDDEN.has(t.upper))||parsed.tokens.some((t,i)=>t.upper==="INTO"&&["OUTFILE","DUMPFILE"].includes(parsed.tokens[i+1]?.upper))||parsed.tokens.some((t,i)=>t.upper==="FOR"&&parsed.tokens[i+1]?.upper==="UPDATE"))errors.push(issue("SQL_FORBIDDEN_KEYWORD","변경, 파일 접근, 잠금 또는 관리 구문은 허용되지 않습니다."));
 if(parsed.functions.some(f=>BAD_FUNCTIONS.has(f)))errors.push(issue("SQL_FORBIDDEN_FUNCTION","시간 지연 또는 외부 자원 접근 함수는 허용되지 않습니다."));
 if(parsed.joinCount>policy.maxJoins)errors.push(issue("SQL_TOO_MANY_JOINS",`JOIN은 최대 ${policy.maxJoins}개까지 허용됩니다.`));if(parsed.subqueryDepth>policy.maxSubqueryDepth)errors.push(issue("SQL_VALIDATION_FAILED","서브쿼리 깊이가 제한을 초과했습니다."));
 const tables=parsed.tables.map(name=>name.includes(".")?name.split(".").at(-1)!:name);for(const name of parsed.tables){const parts=name.split(".");if(parts.length>1&&(SYSTEM.has(parts[0].toLowerCase())||parts[0].toLowerCase()!==connection.databaseName.toLowerCase()))errors.push(issue("SQL_SYSTEM_SCHEMA_ACCESS_DENIED","현재 선택된 DB와 system schema 외부 접근은 차단됩니다."));}
 let bundle:SchemaBundle;try{bundle=schemaOverride??(await loadSchemaContext(connection)).bundle;}catch{return {...base(),errors:[...errors,issue("SQL_VALIDATION_FAILED","최신 스키마를 불러올 수 없습니다.",true)]};}
 const byTable=new Map(bundle.tables.map(d=>[d.table.name.toLowerCase(),d.table]));for(const table of tables)if(!byTable.has(table.toLowerCase()))errors.push(issue("SQL_TABLE_NOT_FOUND",`${table} 테이블이 최신 스키마에 없습니다.`,true,{table}));
 const referencedColumns:string[]=[];for(const col of parsed.columns){if(!col.qualifier){const matches=tables.filter(t=>byTable.get(t.toLowerCase())?.columns.some(c=>c.name.toLowerCase()===col.name.toLowerCase()));if(matches.length===1)referencedColumns.push(`${matches[0]}.${col.name}`);else if(matches.length===0)errors.push(issue("SQL_COLUMN_NOT_FOUND",`${col.name} 컬럼이 참조 테이블에 없습니다.`,true,{column:col.name}));else errors.push(issue("SQL_AMBIGUOUS_COLUMN",`${col.name} 컬럼은 여러 테이블에 있어 테이블 alias가 필요합니다.`,true,{column:col.name}));continue;}const qualified=parsed.aliases.get(col.qualifier.toLowerCase());if(!qualified)continue;const table=qualified.split(".").at(-1)!;referencedColumns.push(`${table}.${col.name}`);const doc=byTable.get(table.toLowerCase());if(doc&&!doc.columns.some(c=>c.name.toLowerCase()===col.name.toLowerCase()))errors.push(issue("SQL_COLUMN_NOT_FOUND",`${table} 테이블에 ${col.name} 컬럼이 없습니다.`,true,{table,column:col.name}));}
 const max=Math.min(Math.max(1,requestedMaxRows??policy.defaultMaxRows),policy.absoluteMaxRows);let executionSql=parsed.normalizedSql;if(parsed.limit===null){if(!parsed.aggregateOnly)warnings.push(issue("SQL_LIMIT_REQUIRED",`서버에서 최대 ${max}행 제한을 적용합니다.`,true));executionSql=`SELECT * FROM (${parsed.normalizedSql}) AS tq_readonly_result LIMIT ${max+1}`;}else if(parsed.limit>max){warnings.push(issue("SQL_LIMIT_EXCEEDED",`요청 LIMIT을 서버 상한 ${max}행으로 제한합니다.`));executionSql=`SELECT * FROM (${parsed.normalizedSql}) AS tq_readonly_result LIMIT ${max+1}`;}
 return {...base(),valid:errors.length===0,readonly:!errors.some(e=>["SQL_NOT_READONLY","SQL_FORBIDDEN_KEYWORD","SQL_FORBIDDEN_FUNCTION","SQL_MULTIPLE_STATEMENTS"].includes(e.code)),errors,warnings,normalizedSql:parsed.normalizedSql,executionSql,appliedMaxRows:max,referencedColumns};
 function base(){return {valid:false,readonly:true,errors,warnings,referencedTables:tables,referencedColumns:[] as string[]};}
}
