import type {ToolContext} from "@/lib/server/agent/types";
import type {ToolSecurityMetadata,AuthorizationDecision,AuthorizationRequest,SecurityEnvironment} from "./security-types";
import {evaluatePolicy} from "./policy-engine";
import {SecurityError} from "./security-errors";
import {consumeSecurityRateLimit} from "./rate-limit-service";
const safeId=/^[A-Za-z0-9_.:*-]{1,160}$/;
export async function authorizeTool(input:{context:ToolContext;toolName:string;metadata:ToolSecurityMetadata;toolInput:Readonly<Record<string,unknown>>}){
 const [{getResourceGrants,getSecurityActor},{severityFor,writeSecurityAudit}]=await Promise.all([import("./permission-repository"),import("./security-audit-service")]);
 const actor=input.context.securityActor??await getSecurityActor(input.context.userId),resourceId=resolveResourceId(input.metadata,input.toolInput,input.context),environment=resolveEnvironment(input.metadata,input.toolInput),request:AuthorizationRequest={actor,action:input.metadata.action,resource:{type:input.metadata.resourceType,id:resourceId,environment,ownerId:input.metadata.resourceType==="conversation"?actor.userId:null,organizationId:actor.organizationId,classification:input.metadata.classification??"internal"},context:{conversationId:input.context.conversationId,connectionId:input.context.connectionId,agentRunId:null,toolName:input.toolName}};
 const grants=resourceId?await getResourceGrants(actor,input.metadata.resourceType,resourceId):[],decision=evaluatePolicy(request,grants);
 await writeSecurityAudit({eventType:decision.allowed?"authorization_allowed":"authorization_denied",severity:severityFor(decision.reasonCode,decision.allowed),userId:actor.userId,organizationId:actor.organizationId,conversationId:input.context.conversationId,toolName:input.toolName,resourceType:input.metadata.resourceType,resourceId,action:input.metadata.action,decision:decision.allowed?"allow":"deny",reasonCode:decision.reasonCode,metadata:{appliedPolicies:decision.appliedPolicies}}).catch(()=>undefined);
 if(!decision.allowed)throw new SecurityError(decision.reasonCode as never);if(decision.obligations.requireFreshAuthentication){const age=actor.authenticatedAt?Date.now()-actor.authenticatedAt*1000:Infinity;if(age>15*60_000)throw new SecurityError("FRESH_AUTHENTICATION_REQUIRED");}
 const rateLimit=consumeSecurityRateLimit({userId:actor.userId,organizationId:actor.organizationId,toolName:input.toolName,resourceId,riskLevel:input.metadata.riskLevel});return{actor,decision,resourceId,environment,rateLimit};
}
function resolveResourceId(metadata:ToolSecurityMetadata,input:Readonly<Record<string,unknown>>,context:ToolContext){const value=metadata.resourceIdInput?input[metadata.resourceIdInput]:metadata.resourceType==="db_connection"||metadata.resourceType==="schema"||metadata.resourceType==="sql"?context.connectionId:metadata.resourceType==="conversation"?context.conversationId:"*";const id=String(value??"*");if(!safeId.test(id))throw new SecurityError("RESOURCE_NOT_ASSIGNED");return id;}
function resolveEnvironment(metadata:ToolSecurityMetadata,input:Readonly<Record<string,unknown>>):SecurityEnvironment|null{const value=metadata.environment??input.environment;if(value===undefined||value===null)return process.env.NODE_ENV==="production"?"production":"development";if(["local","development","staging","production"].includes(String(value)))return value as SecurityEnvironment;throw new SecurityError("RESOURCE_ENVIRONMENT_DENIED");}
export function requireDecision(decision:AuthorizationDecision){if(!decision.allowed)throw new SecurityError(decision.reasonCode as never);return decision;}
export async function authorizeApiAction(input:{actor:import("./security-types").SecurityActor;resourceType:import("./security-types").SecurityResourceType;resourceId:string;action:import("./security-types").SecurityAction;environment?:SecurityEnvironment;classification?:import("./security-types").DataClassification}){const [{getResourceGrants},{severityFor,writeSecurityAudit}]=await Promise.all([import("./permission-repository"),import("./security-audit-service")]),grants=await getResourceGrants(input.actor,input.resourceType,input.resourceId),request:AuthorizationRequest={actor:input.actor,action:input.action,resource:{type:input.resourceType,id:input.resourceId,environment:input.environment??(process.env.NODE_ENV==="production"?"production":"development"),ownerId:null,organizationId:input.actor.organizationId,classification:input.classification??"internal"},context:{conversationId:null,connectionId:null,agentRunId:null,toolName:null}},decision=evaluatePolicy(request,grants);await writeSecurityAudit({eventType:decision.allowed?"api_authorization_allowed":"api_authorization_denied",severity:severityFor(decision.reasonCode,decision.allowed),userId:input.actor.userId,organizationId:input.actor.organizationId,resourceType:input.resourceType,resourceId:input.resourceId,action:input.action,decision:decision.allowed?"allow":"deny",reasonCode:decision.reasonCode}).catch(()=>undefined);return requireDecision(decision);}
