import {describe,expect,test,beforeEach} from "bun:test";
import {evaluatePolicy} from "./policy-engine";
import {redactToolResult} from "./result-redaction-service";
import {consumeSecurityRateLimit,resetSecurityRateLimits} from "./rate-limit-service";
import type {AuthorizationRequest,ResourceGrant,SecurityActor} from "./security-types";
const actor=(roles:SecurityActor["roles"]=["user"],organizationId="org-a"):SecurityActor=>({userId:"alice",organizationId,roles,active:true,authenticatedAt:1});
const request=(roles:SecurityActor["roles"],overrides:Partial<AuthorizationRequest["resource"]>={},action:AuthorizationRequest["action"]="read"):AuthorizationRequest=>({actor:actor(roles),action,resource:{type:"schema",id:"1",environment:"development",ownerId:null,organizationId:"org-a",classification:"internal",...overrides},context:{conversationId:"conversation",connectionId:1,agentRunId:null,toolName:"test"}});
const grant=(overrides:Partial<ResourceGrant>={}):ResourceGrant=>({subjectType:"user",subjectId:"alice",resourceType:"schema",resourceId:"1",action:"read",environment:null,deny:false,validFrom:null,validUntil:null,...overrides});
describe("integrated security policy",()=>{
 test("combines role permissions with resource grants",()=>{expect(evaluatePolicy(request(["user"]))).toMatchObject({allowed:true,reasonCode:"ROLE_PERMISSION_ALLOWED"});expect(evaluatePolicy(request([],{},"read"),[grant()])).toMatchObject({allowed:true,reasonCode:"RESOURCE_GRANT_ALLOWED"});expect(evaluatePolicy(request([],{},"read"))).toMatchObject({allowed:false,reasonCode:"ACTION_NOT_ALLOWED"});});
 test("explicit deny wins over roles and grants",()=>{expect(evaluatePolicy(request(["security_admin"]),[grant({deny:true})])).toMatchObject({allowed:false,reasonCode:"EXPLICIT_DENY_APPLIED"});});
 test("isolates organizations and environments",()=>{expect(evaluatePolicy(request(["security_admin"],{organizationId:"org-b"}))).toMatchObject({allowed:false,reasonCode:"CROSS_TENANT_ACCESS_DENIED"});expect(evaluatePolicy(request(["operator"],{type:"screenshot",environment:"production"},"create"))).toMatchObject({allowed:false});});
 test("ignores expired grants and supplies redaction obligations",()=>{const decision=evaluatePolicy(request([],{},"read"),[grant({validUntil:new Date(0)})]);expect(decision.allowed).toBe(false);expect(evaluatePolicy(request(["user"],{classification:"personal"}))).toMatchObject({obligations:{requireAudit:true,allowSensitive:false}});});
});
describe("common result redaction",()=>{test("redacts nested credentials and personal patterns",()=>{const result=redactToolResult({password:"plain",nested:[{Authorization:"Bearer top-secret-token",email:"person@example.com",phone:"010-1234-5678",card:"4111 1111 1111 1111",path:"/root/private/file"}]});expect(JSON.stringify(result.data)).not.toContain("plain");expect(JSON.stringify(result.data)).not.toContain("person@example.com");expect(result.metadata.redacted).toBe(true);expect(result.metadata.maskedTypes).toContain("email");});});
describe("security rate limits",()=>{beforeEach(resetSecurityRateLimits);test("limits by actor, organization, tool and resource and resets",()=>{for(let index=0;index<10;index++)consumeSecurityRateLimit({userId:"alice",organizationId:"org",toolName:"execute_readonly_sql",resourceId:"1",riskLevel:"high"});expect(()=>consumeSecurityRateLimit({userId:"alice",organizationId:"org",toolName:"execute_readonly_sql",resourceId:"1",riskLevel:"high"})).toThrow("요청 한도");resetSecurityRateLimits();expect(()=>consumeSecurityRateLimit({userId:"alice",organizationId:"org",toolName:"execute_readonly_sql",resourceId:"1",riskLevel:"high"})).not.toThrow();});});
