import {createHash,randomUUID} from "node:crypto";
import type {RowDataPacket} from "mysql2/promise";
import {getManagementDbPool} from "@/lib/server/db/management-db";
import {ensureSecuritySchema} from "./permission-repository";
import type {SecuritySeverity} from "./security-types";
import {redactToolResult} from "./result-redaction-service";
export type SecurityAuditEvent=Readonly<{eventType:string;severity:SecuritySeverity;userId:string|null;organizationId:string|null;conversationId?:string|null;agentRunId?:string|null;toolName?:string|null;resourceType?:string|null;resourceId?:string|null;action?:string|null;decision:"allow"|"deny"|"error";reasonCode:string;metadata?:Readonly<Record<string,unknown>>}>;
export async function writeSecurityAudit(event:SecurityAuditEvent){if((process.env.NODE_ENV==="test"||process.argv.some(value=>value.endsWith(".test.ts"))))return"test-security-event";await ensureSecuritySchema();const db=getManagementDbPool(),[previous]=await db.execute<RowDataPacket[]>("SELECT event_hash FROM tq_security_audit ORDER BY created_at DESC,event_id DESC LIMIT 1"),previousHash=previous[0]?.event_hash?String(previous[0].event_hash):null,eventId=randomUUID(),safe=redactToolResult(event.metadata??{},[],4000),metadata=JSON.stringify(safe.data),eventHash=createHash("sha256").update(JSON.stringify({eventId,...event,metadata,previousHash})).digest("hex");await db.execute(`INSERT INTO tq_security_audit(event_id,event_type,severity,user_id,organization_id,conversation_id,agent_run_id,tool_name,resource_type,resource_id,action,decision,reason_code,metadata_json,previous_hash,event_hash) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[eventId,event.eventType,event.severity,event.userId,event.organizationId,event.conversationId??null,event.agentRunId??null,event.toolName??null,event.resourceType??null,event.resourceId??null,event.action??null,event.decision,event.reasonCode,metadata,previousHash,eventHash]);return eventId;}
export async function listSecurityAudit(limit=100){await ensureSecuritySchema();const [rows]=await getManagementDbPool().execute<RowDataPacket[]>("SELECT event_id,event_type,severity,user_id,organization_id,conversation_id,tool_name,resource_type,resource_id,action,decision,reason_code,metadata_json,previous_hash,event_hash,created_at FROM tq_security_audit ORDER BY created_at DESC,event_id DESC LIMIT ?",[Math.min(200,Math.max(1,limit))]);return rows.map(row=>({eventId:row.event_id,eventType:row.event_type,severity:row.severity,userId:row.user_id,organizationId:row.organization_id,conversationId:row.conversation_id,toolName:row.tool_name,resourceType:row.resource_type,resourceId:row.resource_id,action:row.action,decision:row.decision,reasonCode:row.reason_code,metadata:typeof row.metadata_json==="string"?JSON.parse(row.metadata_json):row.metadata_json,previousHash:row.previous_hash,eventHash:row.event_hash,createdAt:new Date(row.created_at).toISOString()}));}
export function severityFor(reasonCode:string,allowed:boolean):SecuritySeverity{if(allowed)return"info";if(reasonCode==="CROSS_TENANT_ACCESS_DENIED"||reasonCode==="SECRET_DETECTED_AND_BLOCKED")return"high";if(reasonCode==="SESSION_SECURITY_VIOLATION")return"critical";return"warning";}
