import type {ToolSecurityMetadata} from "./security-types";
const low=(resourceType:ToolSecurityMetadata["resourceType"],action:ToolSecurityMetadata["action"],extra:Partial<ToolSecurityMetadata>={}):ToolSecurityMetadata=>({resourceType,action,riskLevel:"low",auditLevel:"basic",classification:"internal",...extra});
const medium=(resourceType:ToolSecurityMetadata["resourceType"],action:ToolSecurityMetadata["action"],extra:Partial<ToolSecurityMetadata>={}):ToolSecurityMetadata=>({...low(resourceType,action,extra),riskLevel:"medium",auditLevel:"detailed"});
const high=(resourceType:ToolSecurityMetadata["resourceType"],action:ToolSecurityMetadata["action"],extra:Partial<ToolSecurityMetadata>={}):ToolSecurityMetadata=>({...medium(resourceType,action,extra),riskLevel:"high"});
export const TOOL_SECURITY_POLICIES:Readonly<Record<string,ToolSecurityMetadata>>={
 get_service_capabilities:low("service","read"),get_selected_database_context:low("db_connection","read"),get_schema_summary:low("schema","read"),get_schema_version:low("schema","read"),list_schema_objects:low("schema","list"),search_schema:low("schema","search"),describe_table:low("schema","read"),find_table_relationships:low("schema","search"),
 get_knowledge_capabilities:low("knowledge_document","read"),list_knowledge_documents:low("knowledge_document","list"),search_knowledge_documents:low("knowledge_document","search"),read_knowledge_document:low("knowledge_document","read"),search_business_knowledge:low("business_knowledge","search"),read_business_knowledge:low("business_knowledge","read"),get_column_semantics:low("business_knowledge","read"),get_metric_definition:low("business_knowledge","read"),get_business_relationship:low("business_knowledge","read"),
 validate_readonly_sql:medium("sql","search"),explain_readonly_sql:medium("sql","read"),execute_readonly_sql:high("sql","execute",{classification:"personal",maxRows:200}),
 get_repository_context:low("github_repository","read",{resourceIdInput:"repositoryRole"}),list_repository_tree:low("github_repository","read",{resourceIdInput:"repositoryRole"}),search_repository_code:medium("github_repository","search",{resourceIdInput:"repositoryRole"}),read_repository_file:medium("github_repository","read",{resourceIdInput:"repositoryRole"}),find_repository_references:medium("github_repository","search",{resourceIdInput:"repositoryRole"}),get_file_history:low("github_repository","read",{resourceIdInput:"repositoryRole"}),get_commit_details:low("github_repository","read",{resourceIdInput:"repositoryRole"}),compare_repository_refs:medium("github_repository","read",{resourceIdInput:"repositoryRole"}),
 get_runtime_project_context:low("runtime_project","read"),get_deployment_status:medium("runtime_project","read",{resourceIdInput:"projectId"}),get_process_status:medium("runtime_project","read",{resourceIdInput:"projectId"}),get_port_status:medium("runtime_project","read",{resourceIdInput:"projectId"}),run_project_health_check:medium("runtime_project","read",{resourceIdInput:"projectId"}),get_reverse_proxy_status:medium("runtime_project","read",{resourceIdInput:"projectId"}),get_deployment_report:high("deployment_report","read",{resourceIdInput:"projectId",classification:"confidential"}),compare_deployed_commit_with_repository:medium("runtime_project","read",{resourceIdInput:"projectId"}),get_runtime_capabilities:low("runtime_project","read"),
 get_ui_project_context:low("ui_project","read",{environment:"production"}),open_ui_page:medium("ui_project","read",{resourceIdInput:"uiProjectId"}),inspect_ui_page:medium("ui_project","read",{resourceIdInput:"uiProjectId"}),inspect_ui_element:medium("ui_project","read",{resourceIdInput:"uiProjectId"}),click_ui_element:high("ui_project","read",{resourceIdInput:"uiProjectId"}),navigate_ui_route:medium("ui_project","read",{resourceIdInput:"uiProjectId"}),get_ui_network_summary:medium("ui_project","read",{resourceIdInput:"uiProjectId"}),get_ui_console_summary:medium("ui_project","read",{resourceIdInput:"uiProjectId",classification:"confidential"}),capture_ui_screenshot:high("screenshot","create",{resourceIdInput:"uiProjectId",environment:"production",classification:"personal"}),get_ui_capabilities:low("ui_project","read",{environment:"production"})
};
export function securityPolicyForTool(name:string){return TOOL_SECURITY_POLICIES[name]??null;}
