"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { LogoutButton } from "@/components/logout-button";
import { getSchemaAgeLabel } from "./schema-age";
import type { AdminConnection, AdminFailure, AdminSchemaState } from "./types";

type LoadState = "loading" | "success" | "empty" | "error";
const time = (v: string | null) => v && Number.isFinite(Date.parse(v)) ? new Intl.DateTimeFormat("ko-KR", { dateStyle: "short", timeStyle: "short" }).format(new Date(v)) : "확인하지 못함";
const message = (s: LoadState, empty: string) => s === "loading" ? "불러오는 중…" : s === "empty" ? empty : s === "error" ? "이 영역을 불러오지 못했습니다. 다른 관리 기능은 계속 사용할 수 있습니다." : null;

export function AdminDashboard() {
  const router = useRouter();
  const [connections, setConnections] = useState<AdminConnection[]>([]), [schemas, setSchemas] = useState<AdminSchemaState[]>([]);
  const [gpt, setGpt] = useState<AdminFailure[]>([]), [sql, setSql] = useState<AdminFailure[]>([]);
  const [connectionState, setConnectionState] = useState<LoadState>("loading"), [schemaState, setSchemaState] = useState<LoadState>("loading"), [gptState, setGptState] = useState<LoadState>("loading"), [sqlState, setSqlState] = useState<LoadState>("loading");
  const [busyId, setBusyId] = useState<number | null>(null), [detail, setDetail] = useState<AdminFailure | null>(null);
  async function request(url: string, init?: RequestInit) { const r = await fetch(url, { cache: "no-store", ...init }); if (r.status === 401) { router.replace("/login"); throw new Error(); } if (!r.ok) throw new Error(); return r.json() as Promise<Record<string, unknown>>; }
  async function loadConnections() { setConnectionState("loading"); try { const b = await request("/api/db-connections?includeInactive=true"), items = Array.isArray(b.connections) ? b.connections as AdminConnection[] : []; setConnections(items); setConnectionState(items.length ? "success" : "empty"); return items; } catch { setConnectionState("error"); return []; } }
  async function loadSchemas(items: AdminConnection[]) { setSchemaState("loading"); try { const values = await Promise.all(items.map(async c => (await request(`/api/db-connections/${c.id}/schema/snapshots?limit=1`)).latest as AdminSchemaState)); setSchemas(values.filter(Boolean)); setSchemaState(values.length ? "success" : "empty"); } catch { setSchemaState("error"); } }
  async function loadFailures(kind: "gpt" | "sql") { const updateState = kind === "gpt" ? setGptState : setSqlState; updateState("loading"); try { const path = kind === "gpt" ? "/api/analysis/history?status=failed&limit=20" : "/api/query/history?status=failed&limit=20", b = await request(path), items = Array.isArray(b.items) ? b.items as AdminFailure[] : []; (kind === "gpt" ? setGpt : setSql)(items); updateState(items.length ? "success" : "empty"); } catch { updateState("error"); } }
  async function reload() { const items = await loadConnections(); await Promise.all([loadSchemas(items), loadFailures("gpt"), loadFailures("sql")]); }
  useEffect(() => { void reload(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  async function testConnection(id: number) { setBusyId(id); try { await request(`/api/db-connections/${id}/test`, { method: "POST" }); await loadConnections(); } catch { setConnectionState("error"); } finally { setBusyId(null); } }
  async function refreshSchema(id: number) { if (!window.confirm("스키마를 수동 갱신하시겠습니까? 기존 최신 성공 버전은 실패 시 유지됩니다.")) return; setBusyId(id); try { await request(`/api/db-connections/${id}/schema/collect`, { method: "POST" }); await loadSchemas(connections); } catch { setSchemaState("error"); } finally { setBusyId(null); } }
  const name = (id: number) => connections.find(c => c.id === id)?.displayName ?? `DB #${id}`;
  return <main className="admin-shell"><header className="analysis-topbar"><div className="analysis-brand"><span>TQ</span><div><small>TENA INTERNAL TOOLS</small><strong>Tena Query Desk</strong></div><b>관리</b></div><div className="topbar-tools"><Link className="nav-button" href="/">분석 화면</Link><button className="nav-button" onClick={() => void reload()}>새로고침</button><LogoutButton /></div></header><div className="admin-content">
    <div className="admin-heading"><div><span>OPERATIONS</span><h1>최소 관리 화면</h1><p>연결, 스키마와 최근 실패를 영역별로 독립 점검합니다.</p></div><button className="primary-button" disabled title="대상 DB CRUD API가 제공되지 않았습니다.">신규 DB 등록</button></div>
    <section className="admin-panel"><header><h2>대상 DB 연결 상태</h2><span>접속정보는 표시하지 않습니다.</span></header>{message(connectionState, "등록된 대상 DB가 없습니다.") ?? <div className="admin-table-wrap"><table><thead><tr><th>표시 이름 / 키</th><th>종류</th><th>활성</th><th>최근 상태</th><th>확인 시각</th><th>동작</th></tr></thead><tbody>{connections.map(c => <tr key={c.id}><td><strong>{c.displayName}</strong><small>{c.connectionKey}</small></td><td>MySQL</td><td>{c.active ? "활성" : "비활성"}</td><td>{!c.active ? "비활성" : c.connectionStatus === "healthy" ? "정상" : c.connectionStatus === "failed" ? "실패" : "미확인"}</td><td>{time(c.checkedAt)}</td><td><button disabled={busyId === c.id || !c.active} onClick={() => void testConnection(c.id)}>연결 테스트</button><button disabled title="수정 API 미구현">수정</button><button disabled title="상태 변경 API 미구현">{c.active ? "비활성화" : "활성화"}</button></td></tr>)}</tbody></table></div>}</section>
    <section className="admin-panel"><header><h2>최신 스키마 상태</h2><span>7일 갱신 권장 · 30일 오래됨</span></header>{message(schemaState, "생성된 스키마가 없습니다.") ?? <div className="admin-table-wrap"><table><thead><tr><th>대상 DB</th><th>버전 / 상태</th><th>구조</th><th>생성 시각</th><th>해시 / 파일</th><th>동작</th></tr></thead><tbody>{schemas.map(s => <tr key={s.connectionId}><td>{name(s.connectionId)}</td><td>{s.versionNo ? `v${s.versionNo}` : "버전 없음"} · {s.status}</td><td>{s.tableCount ?? "?"} tables · {s.viewCount ?? "?"} views</td><td>{time(s.generatedAt)} {getSchemaAgeLabel(s.generatedAt) && <b className="status-warning">{getSchemaAgeLabel(s.generatedAt)}</b>}</td><td>{s.schemaHash?.slice(0, 10) ?? "해시 없음"} · {s.filesPresent ? "파일 확인" : "파일 누락"}</td><td><button disabled={busyId === s.connectionId || s.status === "processing"} onClick={() => void refreshSchema(s.connectionId)}>{busyId === s.connectionId ? "갱신 중…" : "수동 갱신"}</button></td></tr>)}</tbody></table></div>}</section>
    <div className="admin-failures">{([["최근 GPT 실패", gptState, gpt], ["최근 SQL 실행 실패", sqlState, sql]] as const).map(([title, state, items]) => <section className="admin-panel" key={title}><header><h2>{title}</h2><span>최근 20건</span></header>{message(state, "최근 실패가 없습니다.") ?? <div className="failure-list">{items.map(item => <button key={item.id} onClick={() => setDetail(item)}><strong>{name(item.connectionId)} · {time(item.createdAt)}</strong><span>{item.preview}</span><small>{item.errorMessage}</small></button>)}</div>}</section>)}</div>
  </div>{detail && <div className="admin-modal-backdrop" onClick={() => setDetail(null)}><section className="admin-modal" role="dialog" aria-modal="true" onClick={e => e.stopPropagation()}><header><h2>{detail.kind === "gpt" ? "GPT 실패 상세" : "SQL 실행 실패 상세"}</h2><button onClick={() => setDetail(null)}>닫기</button></header><dl><dt>ID</dt><dd>#{detail.id}</dd><dt>대상 DB</dt><dd>{name(detail.connectionId)}</dd><dt>발생 시각</dt><dd>{time(detail.createdAt)}</dd><dt>내용</dt><dd><pre>{detail.preview}</pre></dd><dt>안전한 오류</dt><dd>{detail.errorMessage}</dd></dl><p>상세 확인만 제공하며 SQL은 자동 실행하지 않습니다.</p></section></div>}</main>;
}
