import { afterEach,describe,expect,test } from "bun:test";import { mkdtemp,mkdir,rm,symlink,writeFile } from "node:fs/promises";import { tmpdir } from "node:os";import path from "node:path";import { buildKnowledgeIndex } from "./loader";import { listKnowledge,readKnowledge,searchKnowledge } from "./service";
let root="";afterEach(async()=>{if(root)await rm(root,{recursive:true,force:true});root="";});
const doc=(id="service-guide",status="active",body="# 등록 절차\n신규 DB 연결 키와 비밀번호를 입력합니다.\n# 오류 대응\nlocalhost와 권한을 확인합니다.")=>`---\nid: ${id}\ntitle: DB 등록 가이드\ncategory: service\ntags: ["DB 등록", "connection key"]\nstatus: ${status}\nupdated_at: 2026-07-29\nversion: 1\naudience: ["admin"]\nrelated_documents: ["other-guide"]\nrelated_tools: ["get_service_capabilities"]\nrelated_routes: ["/admin"]\nsource_of_truth: true\nsummary: 신규 DB 등록 절차\n---\n${body}`;
async function setup(){root=await mkdtemp(path.join(tmpdir(),"knowledge-"));await mkdir(path.join(root,"service"));await writeFile(path.join(root,"service","guide.md"),doc());return buildKnowledgeIndex(root);}
describe("knowledge loader and index",()=>{
 test("parses metadata, sections, hash and no absolute path",async()=>{const index=await setup(),item=index.documents[0];expect(item.metadata).toMatchObject({id:"service-guide",status:"active",version:1});expect(item.sections.map(x=>x.title)).toEqual(["등록 절차","오류 대응"]);expect(item.contentHash).toMatch(/^[0-9a-f]{64}$/);expect(JSON.stringify(listKnowledge(index,{}))).not.toContain(root);});
 test("rejects missing metadata, duplicate ids, unsupported and hidden files",async()=>{root=await mkdtemp(path.join(tmpdir(),"knowledge-invalid-"));await writeFile(path.join(root,"bad.md"),"# no metadata");await expect(buildKnowledgeIndex(root)).rejects.toMatchObject({code:"KNOWLEDGE_DOCUMENT_INVALID_METADATA"});await rm(path.join(root,"bad.md"));await writeFile(path.join(root,"a.md"),doc());await writeFile(path.join(root,"b.md"),doc());await expect(buildKnowledgeIndex(root)).rejects.toMatchObject({code:"KNOWLEDGE_DOCUMENT_DUPLICATED"});await rm(path.join(root,"b.md"));await writeFile(path.join(root,"bad.txt"),"x");await expect(buildKnowledgeIndex(root)).rejects.toMatchObject({code:"KNOWLEDGE_PATH_NOT_ALLOWED"});});
 test("rejects symlinks and files outside the root",async()=>{root=await mkdtemp(path.join(tmpdir(),"knowledge-link-"));const outside=path.join(root,"..","outside-secret");await writeFile(outside,"secret");await symlink(outside,path.join(root,"link.md"));await expect(buildKnowledgeIndex(root)).rejects.toMatchObject({code:"KNOWLEDGE_PATH_NOT_ALLOWED"});await rm(outside,{force:true});});
 test("reflects changed and deleted documents on rebuild",async()=>{const first=await setup(),hash=first.contentHash;await writeFile(path.join(root,"service","guide.md"),doc("service-guide","active","# 변경\n새 내용"));const second=await buildKnowledgeIndex(root);expect(second.contentHash).not.toBe(hash);await rm(path.join(root,"service","guide.md"));expect((await buildKnowledgeIndex(root)).documents).toHaveLength(0);});
});
describe("knowledge search and read",()=>{
 test("lists statuses explicitly and paginates",async()=>{await setup();await writeFile(path.join(root,"service","old.md"),doc("old-guide","deprecated"));const all=await buildKnowledgeIndex(root);expect(listKnowledge(all,{}).total).toBe(1);expect(listKnowledge(all,{status:"deprecated"}).documents[0].status).toBe("deprecated");expect(()=>listKnowledge(all,{pageSize:51})).toThrow();});
 test("scores title, tags, headings and Korean or English body with filters",async()=>{const index=await setup();expect(searchKnowledge(index,{query:"DB 등록",limit:10}).matches[0].matchedBy).toContain("title");expect(searchKnowledge(index,{query:"connection-key",audience:"admin"}).matches[0].matchedBy).toContain("tag");expect(searchKnowledge(index,{query:"localhost",category:"service"}).matches[0].matchedBy).toContain("body");expect(searchKnowledge(index,{query:"없는 내용"}).matches).toEqual([]);});
 test("reads full or selected sections with truncation and safe ids",async()=>{const index=await setup();expect(readKnowledge(index,{documentId:"service-guide",section:"오류 대응",maxChars:500}).content).toContain("localhost");expect(readKnowledge(index,{documentId:"service-guide",maxChars:500}).relatedDocuments).toContain("other-guide");expect(()=>readKnowledge(index,{documentId:"service-guide",section:"없음"})).toThrow();expect(()=>readKnowledge(index,{documentId:"../.env"})).toThrow();});
});
