import { createHash } from "node:crypto";
import { lstat, readFile, readdir, realpath } from "node:fs/promises";
import path from "node:path";
import type { KnowledgeDocument, KnowledgeIndex, KnowledgeMetadata, KnowledgeSection, KnowledgeStatus } from "./types";
import { KnowledgeError } from "./types";
const MAX_FILE=200_000,STATUSES=new Set<KnowledgeStatus>(["active","draft","deprecated","archived"]),ID=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
const array=(value:string|undefined)=>{if(!value)return [];try{const parsed=JSON.parse(value);return Array.isArray(parsed)&&parsed.every(x=>typeof x==="string")?parsed:[];}catch{return [];}};
const safeContent=(value:string)=>value.replace(/-----BEGIN [^-]+PRIVATE KEY-----[\s\S]*?-----END [^-]+PRIVATE KEY-----/g,"[REDACTED PRIVATE KEY]").replace(/\bsk-[A-Za-z0-9_-]{16,}\b/g,"[REDACTED API KEY]").replace(/\b(password|secret|token)\s*[:=]\s*\S+/gi,"$1: [REDACTED]");
function parse(content:string,relativePath:string):KnowledgeDocument{if(content.length>MAX_FILE)throw new KnowledgeError("KNOWLEDGE_DOCUMENT_TOO_LARGE","지식 문서가 허용 크기를 초과했습니다.",false);const match=/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/.exec(content);if(!match)throw new KnowledgeError("KNOWLEDGE_DOCUMENT_INVALID_METADATA","지식 문서 메타데이터가 올바르지 않습니다.",false);const raw=Object.fromEntries(match[1].split(/\r?\n/).filter(Boolean).map(line=>{const at=line.indexOf(":");return at<1?[line,""]:[line.slice(0,at).trim(),line.slice(at+1).trim()];})),status=raw.status as KnowledgeStatus,version=Number(raw.version);if(!ID.test(raw.id??"")||!raw.title||!raw.category||!STATUSES.has(status)||!/^\d{4}-\d{2}-\d{2}$/.test(raw.updated_at??"")||!Number.isSafeInteger(version)||version<1||array(raw.tags).length===0)throw new KnowledgeError("KNOWLEDGE_DOCUMENT_INVALID_METADATA","지식 문서의 필수 메타데이터가 올바르지 않습니다.",false);const body=safeContent(match[2].trim()),headings=[...body.matchAll(/^(#{1,6})\s+(.+)$/gm)],sections:KnowledgeSection[]=headings.map((heading,index)=>({title:heading[2].trim(),level:heading[1].length,start:heading.index!,end:headings[index+1]?.index??body.length}));const metadata:KnowledgeMetadata={id:raw.id,title:raw.title,category:raw.category,tags:array(raw.tags),status,updatedAt:raw.updated_at,version,audience:array(raw.audience),relatedDocuments:array(raw.related_documents),relatedTools:array(raw.related_tools),relatedRoutes:array(raw.related_routes),sourceOfTruth:raw.source_of_truth==="true",summary:raw.summary||body.replace(/^#+\s+/gm,"").slice(0,240)};const searchText=[metadata.title,metadata.category,...metadata.tags,...metadata.audience,...metadata.relatedTools,...metadata.relatedRoutes,metadata.summary,...sections.map(x=>x.title),body].join(" ");return {metadata,relativePath,body,sections,contentHash:hash(content),searchText};}
async function files(root:string,directory:string):Promise<string[]>{const entries=await readdir(directory,{withFileTypes:true}),result:string[]=[];for(const entry of entries){if(entry.name.startsWith("."))throw new KnowledgeError("KNOWLEDGE_PATH_NOT_ALLOWED","숨김 파일은 지식 문서로 사용할 수 없습니다.",false);const absolute=path.join(directory,entry.name),stat=await lstat(absolute);if(stat.isSymbolicLink())throw new KnowledgeError("KNOWLEDGE_PATH_NOT_ALLOWED","symbolic link는 지식 문서에서 허용되지 않습니다.",false);if(stat.isDirectory())result.push(...await files(root,absolute));else if(path.extname(entry.name)!==".md")throw new KnowledgeError("KNOWLEDGE_PATH_NOT_ALLOWED","Markdown 이외 파일은 지식 문서에서 허용되지 않습니다.",false);else result.push(absolute);}return result;}
export async function buildKnowledgeIndex(root=path.join(process.cwd(),"knowledge")):Promise<KnowledgeIndex>{let resolved:string;try{resolved=await realpath(root);}catch{throw new KnowledgeError("KNOWLEDGE_ROOT_NOT_FOUND","지식 문서 루트를 찾을 수 없습니다.",false);}const documents:KnowledgeDocument[]=[];for(const file of await files(resolved,resolved)){const actual=await realpath(file);if(!actual.startsWith(`${resolved}${path.sep}`))throw new KnowledgeError("KNOWLEDGE_PATH_NOT_ALLOWED","허용되지 않은 문서 경로입니다.",false);documents.push(parse(await readFile(actual,"utf8"),path.relative(resolved,actual).split(path.sep).join("/")));}const ids=new Set<string>();for(const document of documents){if(ids.has(document.metadata.id))throw new KnowledgeError("KNOWLEDGE_DOCUMENT_DUPLICATED","중복된 지식 문서 ID가 있습니다.",false,{documentId:document.metadata.id});ids.add(document.metadata.id);}documents.sort((a,b)=>a.metadata.id.localeCompare(b.metadata.id));return {documents,lastIndexedAt:new Date().toISOString(),contentHash:hash(documents.map(x=>x.contentHash).join(""))};}
