import { describe, expect, test } from "bun:test";
import { parseGeneratedQueryResponse } from "./response-schema";
const readOnly={ requestType:"select",answer:"설명",sql:"SELECT id FROM orders",referencedTables:["orders"],assumptions:[],warnings:[],riskLevel:"read_only",transactionGuidance:{applicable:false,summary:null},executionPlan:null };
const change=(overrides:Record<string,unknown>={})=>({requestType:"ddl_dml_reference",answer:"별도 검토 후 실행",sql:"UPDATE orders SET status = 'done' WHERE id = 1",referencedTables:["orders"],assumptions:[],warnings:["운영 승인 필요"],riskLevel:"data_change",transactionGuidance:{applicable:true,summary:"중간 오류 시 COMMIT하지 말고 같은 세션에서 ROLLBACK"},executionPlan:{preChecks:["SELECT id FROM orders WHERE id = 1"],statements:["START TRANSACTION","UPDATE orders SET status = 'done' WHERE id = 1","COMMIT"],postChecks:["SELECT id FROM orders WHERE id = 1"],rollbackOrRecovery:["오류 시 같은 세션에서 ROLLBACK"]},...overrides});
describe("structured GPT response",()=>{
 test("keeps read-only response compatible",()=>expect(parseGeneratedQueryResponse(readOnly,new Set(["orders"])).riskLevel).toBe("read_only"));
 test("accepts guarded DML plan",()=>{const r=parseGeneratedQueryResponse(change(),new Set(["orders"]));expect(r.transactionGuidance.applicable).toBe(true);expect(r.warnings[0]).toContain("참고용");});
 test("rejects WHERE-less mutation and missing rollback",()=>{expect(()=>parseGeneratedQueryResponse(change({executionPlan:{preChecks:["SELECT 1"],statements:["UPDATE orders SET status='x'","COMMIT"],postChecks:["SELECT 1"],rollbackOrRecovery:["백업 확인"]}}),new Set(["orders"]))).toThrow();expect(()=>parseGeneratedQueryResponse(change({transactionGuidance:{applicable:true,summary:"완료 후 COMMIT"},executionPlan:{preChecks:["SELECT 1"],statements:["UPDATE orders SET status='x' WHERE id=1","COMMIT"],postChecks:["SELECT 1"],rollbackOrRecovery:["담당자 확인"]}}),new Set(["orders"]))).toThrow();});
 test("adds DDL implicit commit and mixed atomicity warnings",()=>{const r=parseGeneratedQueryResponse(change({riskLevel:"schema_change",sql:"ALTER TABLE orders ADD COLUMN memo VARCHAR(10); UPDATE orders SET memo='x' WHERE id=1",transactionGuidance:{applicable:true,summary:"UPDATE 구간만 트랜잭션 적용; 오류 시 ROLLBACK"},executionPlan:{preChecks:["SHOW CREATE TABLE orders"],statements:["ALTER TABLE orders ADD COLUMN memo VARCHAR(10)","START TRANSACTION","UPDATE orders SET memo='x' WHERE id=1","COMMIT"],postChecks:["SHOW CREATE TABLE orders"],rollbackOrRecovery:["DDL은 별도 역변경, DML 오류는 ROLLBACK"]}}),new Set(["orders"]));expect(r.warnings.join(" ")).toContain("암시적 커밋");expect(r.warnings.join(" ")).toContain("전체 원자성");});
 test("rejects destructive response without warning and hallucinated tables",()=>{expect(()=>parseGeneratedQueryResponse(change({riskLevel:"destructive",warnings:[]}),new Set(["orders"]))).toThrow();expect(()=>parseGeneratedQueryResponse({...readOnly,referencedTables:["missing"]},new Set(["orders"]))).toThrow();});
});
