import { DEFAULT_AGENT_LIMITS } from "./limits";
import type { AgentToolDefinition } from "./types";
import { KNOWLEDGE_TYPES } from "@/lib/server/business-knowledge/business-knowledge-types";

const common = { requiresConnection: true, timeoutMs: DEFAULT_AGENT_LIMITS.toolTimeoutMs, maxResultCharacters: DEFAULT_AGENT_LIMITS.maxToolResultCharacters, sensitiveKeys: ["password", "token", "secretValue"] } as const;
export const businessKnowledgeAgentTools: ReadonlyArray<AgentToolDefinition> = [
  { name: "search_business_knowledge", description: "상태, 정상·완료·유효 여부, 집계 기준, 대표 객체, 제외 규칙, 논리 관계 또는 민감도처럼 스키마만으로 확정할 수 없는 업무 의미가 필요한 경우 먼저 검색한다. 검색 결과가 없어도 의미를 추측하지 않는다.", inputSchema: { type: "object", additionalProperties: false, properties: { query: { type: "string", minLength: 1, maxLength: 500 }, types: { type: "array", items: { type: "string", enum: KNOWLEDGE_TYPES }, maxItems: 7 }, limit: { type: "integer", minimum: 1, maximum: 20 } }, required: ["query", "types", "limit"] }, ...common, async execute(context, input) { const {searchActiveBusinessKnowledge}=await import("@/lib/server/business-knowledge/business-knowledge-service");return { matches: await searchActiveBusinessKnowledge(context.connectionId!, String(input.query), input.types as typeof KNOWLEDGE_TYPES, Number(input.limit)) }; } },
  { name: "read_business_knowledge", description: "검색된 active 업무 정의의 구조화된 상태값, 대상, 지표, 포함·제외 조건, 출처, 버전과 스키마 검증 결과를 읽는다. SQL에 반영하기 전 상세 기준을 확인한다.", inputSchema: { type: "object", additionalProperties: false, properties: { knowledgeId: { type: "string", minLength: 36, maxLength: 36 } }, required: ["knowledgeId"] }, ...common, async execute(context, input) { const {readBusinessKnowledge}=await import("@/lib/server/business-knowledge/business-knowledge-service");return readBusinessKnowledge(String(input.knowledgeId), context.connectionId!); } },
  { name: "get_column_semantics", description: "상태 코드 의미 또는 개인정보·비밀정보 등 특정 컬럼의 공식 업무 의미와 민감도를 확인한다. 정의가 없으면 없다고 반환하며 컬럼명으로 의미를 만들지 않는다.", inputSchema: { type: "object", additionalProperties: false, properties: { tableName: { type: "string", minLength: 1, maxLength: 128 }, columnName: { type: "string", minLength: 1, maxLength: 128 } }, required: ["tableName", "columnName"] }, ...common, async execute(context, input) { const {getColumnSemantics}=await import("@/lib/server/business-knowledge/business-knowledge-service");return getColumnSemantics(context.connectionId!, String(input.tableName), String(input.columnName)); } },
  { name: "get_metric_definition", description: "건수, 고객 수, 매출, 평균 또는 비율 SQL을 작성하기 전에 현재 DB의 공식 지표 계산 기준을 확인한다. 충돌 시 하나를 임의 선택하지 않는다.", inputSchema: { type: "object", additionalProperties: false, properties: { metric: { type: "string", minLength: 1, maxLength: 160 } }, required: ["metric"] }, ...common, async execute(context, input) { const {getMetricDefinition}=await import("@/lib/server/business-knowledge/business-knowledge-service");return getMetricDefinition(context.connectionId!, String(input.metric)); } },
  { name: "get_business_relationship", description: "외래키가 없거나 구조 관계와 운영상 조인 관계를 비교해야 할 때 논리 관계를 조회한다. 실제 foreign key, logical, inferred, legacy 구분을 유지한다.", inputSchema: { type: "object", additionalProperties: false, properties: { sourceTable: { type: "string", minLength: 1, maxLength: 128 }, targetConcept: { type: "string", minLength: 1, maxLength: 160 } }, required: ["sourceTable", "targetConcept"] }, ...common, async execute(context, input) { const {getBusinessRelationship}=await import("@/lib/server/business-knowledge/business-knowledge-service");return getBusinessRelationship(context.connectionId!, String(input.sourceTable), String(input.targetConcept)); } },
];
