import { DEFAULT_AGENT_LIMITS } from "./limits";
import type { AgentToolDefinition } from "./types";
import { buildKnowledgeIndex } from "@/lib/server/knowledge/loader";
import { listKnowledge, readKnowledge, searchKnowledge } from "@/lib/server/knowledge/service";
import type { KnowledgeStatus } from "@/lib/server/knowledge/types";
const policy={requiresConnection:false,timeoutMs:DEFAULT_AGENT_LIMITS.toolTimeoutMs,timeoutErrorCode:"KNOWLEDGE_TOOL_TIMEOUT",maxResultCharacters:DEFAULT_AGENT_LIMITS.maxToolResultCharacters,sensitiveKeys:["relativePath","path","password","secret","token","apiKey"]} as const;
export const knowledgeAgentTools:ReadonlyArray<AgentToolDefinition>=[
 {name:"get_knowledge_capabilities",description:"서비스 지식 문서 시스템의 실제 문서 수, category와 검색·읽기 가능 여부를 확인할 때 사용한다.",inputSchema:{type:"object",additionalProperties:false,properties:{},required:[]},...policy,async execute(){const index=await buildKnowledgeIndex();const active=index.documents.filter(x=>x.metadata.status==="active");return {documentSearch:true,documentRead:true,categories:[...new Set(active.map(x=>x.metadata.category))],activeDocumentCount:active.length,lastIndexedAt:index.lastIndexedAt,indexHash:index.contentHash};}},
 {name:"list_knowledge_documents",description:"문서 검색 결과가 없거나 사용 가능한 서비스·운영·업무 문서 목록을 category와 상태별로 살펴볼 때 사용한다.",inputSchema:{type:"object",additionalProperties:false,properties:{category:{type:"string",maxLength:50},status:{type:"string",enum:["active","draft","deprecated","archived"]},page:{type:"integer",minimum:1,maximum:10000},pageSize:{type:"integer",minimum:1,maximum:50}},required:[]},...policy,async execute(_context,input){return listKnowledge(await buildKnowledgeIndex(),input as {category?:string;status?:KnowledgeStatus;page?:number;pageSize?:number});}},
 {name:"search_knowledge_documents",description:"서비스 이용법, 관리자 절차, 장애 대응, 운영 정책 또는 용어를 자연어로 검색할 때 사용한다. 기본적으로 active 문서만 검색한다.",inputSchema:{type:"object",additionalProperties:false,properties:{query:{type:"string",minLength:1,maxLength:500},category:{type:"string",maxLength:50},audience:{type:"string",maxLength:50},status:{type:"string",enum:["active","draft","deprecated","archived"]},limit:{type:"integer",minimum:1,maximum:10}},required:["query"]},...policy,async execute(_context,input){return searchKnowledge(await buildKnowledgeIndex(),input as {query:string;category?:string;audience?:string;status?:KnowledgeStatus;limit?:number});}},
 {name:"read_knowledge_document",description:"검색이나 목록으로 확인한 document ID의 전체 내용 또는 특정 제목 구간을 읽을 때 사용한다. 서버 파일 경로는 받지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{documentId:{type:"string",minLength:1,maxLength:100},section:{type:"string",maxLength:200},endSection:{type:"string",maxLength:200},maxChars:{type:"integer",minimum:500,maximum:8000}},required:["documentId"]},...policy,async execute(_context,input){return readKnowledge(await buildKnowledgeIndex(),input as {documentId:string;section?:string;endSection?:string;maxChars?:number});}},
];
