import { auditAgent } from "./audit";
import { DEFAULT_AGENT_LIMITS, type AgentLimits } from "./limits";
import { AGENT_SYSTEM_PROMPT, FINALIZATION_PROMPT } from "./system-prompt";
import { executeToolCall } from "./tool-executor";
import { createInitialToolRegistry } from "./initial-tools";
import type { ToolRegistry } from "./tool-registry";
import type { AgentMessage, AgentModelClient, RunAgentInput, RunAgentResult } from "./types";
import { OpenAiOperationError } from "@/lib/server/openai/errors";

function finalResponse(value:unknown,described:ReadonlyMap<string,ReadonlySet<string>>):{answer:string;sql:string|null;warnings:string[]}{if(!value||typeof value!=="object")throw new OpenAiOperationError("response_invalid");const item=value as Record<string,unknown>;if(typeof item.answer!=="string"||!item.answer.trim()||item.answer.length>10_000||!(item.sql===null||(typeof item.sql==="string"&&item.sql.length<=50_000))||!Array.isArray(item.warnings)||item.warnings.some(x=>typeof x!=="string"))throw new OpenAiOperationError("response_invalid");const sql=typeof item.sql==="string"?item.sql.trim():null;if(sql){if(!/^\s*(?:SELECT|WITH)\b/i.test(sql)||/\b(?:INSERT|UPDATE|DELETE|REPLACE|CREATE|ALTER|DROP|TRUNCATE|RENAME|GRANT|REVOKE)\b/i.test(sql)||described.size===0)throw new OpenAiOperationError("response_invalid");const aliases=new Map<string,string>(),ctes=new Set([...sql.matchAll(/(?:\bWITH|,)\s*`?([\w$]+)`?\s+AS\s*\(/gi)].map(match=>match[1].toLowerCase()));for(const match of sql.matchAll(/\b(?:FROM|JOIN)\s+`?([\w$]+)`?(?:\s+(?:AS\s+)?`?([\w$]+)`?)?/gi)){const table=match[1];if(ctes.has(table.toLowerCase()))continue;const actual=[...described.keys()].find(name=>name.toLowerCase()===table.toLowerCase());if(!actual)throw new OpenAiOperationError("response_invalid");aliases.set(actual.toLowerCase(),actual);if(match[2]&&!/^(?:WHERE|JOIN|LEFT|RIGHT|INNER|OUTER|ON|GROUP|ORDER|LIMIT)$/i.test(match[2]))aliases.set(match[2].toLowerCase(),actual);}for(const match of sql.matchAll(/`?([\w$]+)`?\s*\.\s*`?([\w$]+)`?/g)){const table=aliases.get(match[1].toLowerCase());if(table&&!described.get(table)?.has(match[2].toLowerCase()))throw new OpenAiOperationError("response_invalid");}}const warnings=(item.warnings as string[]).map(x=>x.trim()).filter(Boolean);if(sql&&!warnings.some(w=>/검증|실행/.test(w)))warnings.push("이 SQL 초안은 실제 DB에서 실행 검증되지 않았습니다.");return {answer:item.answer.trim(),sql,warnings};}
function collectReferences(tool:string,data:unknown,tables:Set<string>,version:{value:string|null},described:Map<string,Set<string>>,documents:Map<string,{id:string;title:string;version:number;updatedAt:string;status:string}>,business:Map<string,import("./types").BusinessKnowledgeReference>){if(!data||typeof data!=="object")return;const item=data as Record<string,unknown>;if(typeof item.schemaVersion==="string")version.value=item.schemaVersion;if(tool==="search_schema"&&Array.isArray(item.matches))for(const match of item.matches)if(match&&typeof match==="object"&&typeof (match as {tableName?:unknown}).tableName==="string")tables.add((match as {tableName:string}).tableName);if(tool==="describe_table"&&item.table&&typeof item.table==="object"&&typeof (item.table as {name?:unknown}).name==="string"){const table=item.table as {name:string;columns?:unknown};tables.add(table.name);described.set(table.name,new Set(Array.isArray(table.columns)?table.columns.flatMap(column=>column&&typeof column==="object"&&typeof (column as {name?:unknown}).name==="string"?[(column as {name:string}).name.toLowerCase()]:[]):[]));}if(tool==="find_table_relationships"){if(typeof item.baseTable==="string")tables.add(item.baseTable);if(Array.isArray(item.relationships))for(const relation of item.relationships)if(relation&&typeof relation==="object"&&typeof (relation as {relatedTable?:unknown}).relatedTable==="string")tables.add((relation as {relatedTable:string}).relatedTable);}if(tool==="read_knowledge_document"&&typeof item.documentId==="string"&&typeof item.title==="string"&&typeof item.version==="number"&&typeof item.updatedAt==="string"&&typeof item.status==="string")documents.set(item.documentId,{id:item.documentId,title:item.title,version:item.version,updatedAt:item.updatedAt,status:item.status});const definition=tool==="get_metric_definition"&&item.definition&&typeof item.definition==="object"?item.definition:tool==="read_business_knowledge"?item:null;if(definition){const entry=definition as Record<string,unknown>;if(typeof entry.id==="string"&&typeof entry.title==="string"&&typeof entry.version==="number"&&typeof entry.type==="string"){const rules=Array.isArray(entry.conditions)?entry.conditions.flatMap(rule=>rule&&typeof rule==="object"?[`${(rule as {ruleType?:string}).ruleType??"rule"}: ${(rule as {columnName?:string}).columnName??"?"} ${(rule as {operator?:string}).operator??"?"}`]:[]):[];business.set(entry.id,{id:entry.id,title:entry.title,version:entry.version,type:entry.type,appliedRules:rules});}}}
export async function runAgent(input:RunAgentInput,dependencies?:Readonly<{client?:AgentModelClient;limits?:AgentLimits;registry?:ToolRegistry;onToolResult?:(call:import("./types").AgentToolCall,result:import("./types").ToolResult)=>Promise<void>|void}>):Promise<RunAgentResult>{
  const limits=dependencies?.limits??DEFAULT_AGENT_LIMITS,client=dependencies?.client??(await import("@/lib/server/openai/agent-client")).openAiAgentClient,registry=dependencies?.registry??createInitialToolRegistry(),started=Date.now();
  if(!input.userMessage.trim()||input.userMessage.length>limits.maxUserMessageCharacters)throw new Error("질문은 1자 이상 5,000자 이하로 입력해 주세요.");
  const messages:AgentMessage[]=[{role:"system",content:AGENT_SYSTEM_PROMPT},...(input.previousMessages??[]).slice(-limits.maxPreviousMessages),{role:"user",content:input.userMessage.trim()}],toolsUsed:Array<{name:string;ok:boolean;durationMs:number}>=[],referenceTables=new Set<string>(),referenceVersion:{value:string|null}={value:null},describedTables=new Map<string,Set<string>>(),referenceDocuments=new Map<string,{id:string;title:string;version:number;updatedAt:string;status:string}>(),referenceBusiness=new Map<string,import("./types").BusinessKnowledgeReference>();
  let toolCalls=0,consecutive=0,lastTool:string|null=null,iterations=0,limitReached=false;
  auditAgent({event:"run_started",userId:input.userId,conversationId:input.conversationId,connectionId:input.connectionId});
  while(iterations<limits.maxIterations&&Date.now()-started<limits.requestTimeoutMs){
    iterations++; let turn; try{turn=await client.complete(messages,registry.toOpenAiTools());auditAgent({event:"model_succeeded",userId:input.userId,conversationId:input.conversationId,connectionId:input.connectionId});}catch(error){auditAgent({event:"model_failed",userId:input.userId,conversationId:input.conversationId,connectionId:input.connectionId,ok:false});throw error;}
    if(turn.type==="final"){const result=finalResponse(turn.value,describedTables);auditAgent({event:"run_finished",userId:input.userId,conversationId:input.conversationId,connectionId:input.connectionId,ok:true,durationMs:Date.now()-started});return {...result,toolsUsed,references:{schemaVersion:referenceVersion.value,tables:[...referenceTables],documents:[...referenceDocuments.values()],businessKnowledge:[...referenceBusiness.values()],toolsUsed:[...new Set(toolsUsed.map(tool=>tool.name))]},conversationId:input.conversationId,metadata:{iterations,completedReason:"final_answer"}};}
    if(!turn.calls.length)throw new OpenAiOperationError("response_invalid");
    messages.push({role:"assistant",content:null,toolCalls:turn.calls});
    for(const call of turn.calls){
      consecutive=call.name===lastTool?consecutive+1:1;lastTool=call.name;
      if(toolCalls>=limits.maxToolCalls||consecutive>limits.maxConsecutiveSameTool){limitReached=true;const blocked={ok:false,tool:call.name,error:{code:"AGENT_LIMIT_REACHED",message:"도구 호출 제한에 도달했습니다.",retryable:false},meta:{durationMs:0}} as const;toolsUsed.push({name:call.name,ok:false,durationMs:0});messages.push({role:"tool",toolCallId:call.id,content:JSON.stringify(blocked)});continue;} toolCalls++;
      const result=await executeToolCall(registry,call,{userId:input.userId,conversationId:input.conversationId,connectionId:input.connectionId,connection:input.connection});await dependencies?.onToolResult?.(call,result);toolsUsed.push({name:call.name,ok:result.ok,durationMs:result.meta.durationMs});if(result.ok)collectReferences(call.name,result.data,referenceTables,referenceVersion,describedTables,referenceDocuments,referenceBusiness);messages.push({role:"tool",toolCallId:call.id,content:JSON.stringify(result)});
    }
    if(limitReached)break;
  }
  limitReached=true;auditAgent({event:"limit_reached",userId:input.userId,conversationId:input.conversationId,connectionId:input.connectionId});messages.push({role:"system",content:FINALIZATION_PROMPT});
  const final=await client.complete(messages,[],{forceFinal:true});if(final.type!=="final")throw new OpenAiOperationError("response_invalid");const result=finalResponse(final.value,describedTables);auditAgent({event:"run_finished",userId:input.userId,conversationId:input.conversationId,connectionId:input.connectionId,ok:true,durationMs:Date.now()-started});return {...result,warnings:[...result.warnings,"도구 호출 제한에 도달하여 확인된 정보만으로 답변했습니다."],toolsUsed,references:{schemaVersion:referenceVersion.value,tables:[...referenceTables],documents:[...referenceDocuments.values()],businessKnowledge:[...referenceBusiness.values()],toolsUsed:[...new Set(toolsUsed.map(tool=>tool.name))]},conversationId:input.conversationId,metadata:{iterations,completedReason:"limit_reached"}};
}
