import { describe, expect, test } from "bun:test";
import { runAgent } from "./orchestrator";
import type { AgentModelClient, AgentModelTurn } from "./types";
const input={userId:"u",connectionId:null,conversationId:"conversation",userMessage:"안녕하세요",connection:null};
function client(turns:AgentModelTurn[],observed?:unknown[][]):AgentModelClient{return {async complete(messages,tools){observed?.push([messages,tools]);const turn=turns.shift();if(!turn)throw new Error("unexpected model call");return turn;}}}
describe("runAgent",()=>{
 test("returns an immediate final answer without tools",async()=>{const result=await runAgent(input,{client:client([{type:"final",value:{answer:"안녕하세요",sql:null,warnings:[]}}])});expect(result.answer).toBe("안녕하세요");expect(result.toolsUsed).toHaveLength(0);});
 test("returns tool results to the model before final answer",async()=>{const observed:unknown[][]=[];const result=await runAgent(input,{client:client([{type:"tool_calls",calls:[{id:"call-1",name:"get_service_capabilities",arguments:"{}"}]},{type:"final",value:{answer:"기능 안내",sql:null,warnings:[]}}],observed)});expect(result.toolsUsed.map(x=>x.name)).toEqual(["get_service_capabilities"]);expect(JSON.stringify(observed[1][0])).toContain("call-1");});
 test("supports consecutive turns with different tools and recoverable tool failure",async()=>{const dbInput={...input,connectionId:1};const result=await runAgent(dbInput,{client:client([{type:"tool_calls",calls:[{id:"bad",name:"missing_tool",arguments:"{}"}]},{type:"tool_calls",calls:[{id:"good",name:"get_service_capabilities",arguments:"{}"}]},{type:"final",value:{answer:"완료",sql:null,warnings:[]}}])});expect(result.toolsUsed).toEqual([expect.objectContaining({name:"missing_tool",ok:false}),expect.objectContaining({name:"get_service_capabilities",ok:true})]);});
 test("requests a tool-free final answer when iteration limit is reached",async()=>{const limits={maxIterations:1,maxToolCalls:10,maxConsecutiveSameTool:3,requestTimeoutMs:10000,toolTimeoutMs:100,maxToolResultCharacters:1000,maxUserMessageCharacters:5000,maxPreviousMessages:8};const result=await runAgent(input,{limits,client:client([{type:"tool_calls",calls:[{id:"1",name:"get_service_capabilities",arguments:"{}"}]},{type:"final",value:{answer:"제한 답변",sql:null,warnings:[]}}])});expect(result.metadata.completedReason).toBe("limit_reached");});
 test("rejects invalid model turns and propagates model failures",async()=>{await expect(runAgent(input,{client:client([{type:"tool_calls",calls:[]}])})).rejects.toThrow();const broken:AgentModelClient={async complete(){throw new Error("model down")}};await expect(runAgent(input,{client:broken})).rejects.toThrow("model down");});
});
