import { describe, expect, test } from "bun:test";
import { runAgent } from "./orchestrator";
import type { AgentModelClient, AgentModelTurn } from "./types";
import { ToolRegistry } from "./tool-registry";
import type { AgentToolDefinition } from "./types";
import { SchemaToolError } from "@/lib/server/schema-tools/types";
const input={userId:"u",connectionId:null,conversationId:"conversation",userMessage:"안녕하세요",connection:null};
function client(turns:AgentModelTurn[],observed?:unknown[][]):AgentModelClient{return {async complete(messages,tools){observed?.push([messages,tools]);const turn=turns.shift();if(!turn)throw new Error("unexpected model call");return turn;}}}
const schemaRegistry=(empty=false)=>new ToolRegistry((["search_schema","describe_table","find_table_relationships","get_schema_summary"] as const).map((name):AgentToolDefinition=>({name,description:name,inputSchema:{type:"object",additionalProperties:true,properties:{},required:[]},requiresConnection:false,timeoutMs:100,maxResultCharacters:1000,sensitiveKeys:[],async execute(_context,args){if(name==="search_schema")return {schemaVersion:"v000003",matches:empty?[]:[{tableName:"orders"}]};if(name==="describe_table"){if(args.tableName==="missing")throw new SchemaToolError("TABLE_NOT_FOUND","없음",true,{candidates:["orders"]});return {schemaVersion:"v000003",table:{name:String(args.tableName),columns:[{name:"id"}]}};}if(name==="find_table_relationships")return {schemaVersion:"v000003",baseTable:"orders",relationships:[{relatedTable:"items"}]};return {schemaVersion:"v000003",tableCount:2};}})));
describe("runAgent",()=>{
 test("returns an immediate final answer without tools",async()=>{const result=await runAgent(input,{client:client([{type:"final",value:{answer:"안녕하세요",sql:null,warnings:[]}}])});expect(result.answer).toBe("안녕하세요");expect(result.toolsUsed).toHaveLength(0);});
 test("returns and exposes tool results for persistent run history",async()=>{const observed:unknown[][]=[],persisted:string[]=[];const result=await runAgent({...input,previousMessages:[{role:"user",content:"이전 질문"},{role:"assistant",content:"이전 답변"}]},{client:client([{type:"tool_calls",calls:[{id:"call-1",name:"get_service_capabilities",arguments:"{}"}]},{type:"final",value:{answer:"기능 안내",sql:null,warnings:[]}}],observed),onToolResult(call){persisted.push(call.id);}});expect(result.toolsUsed.map(x=>x.name)).toEqual(["get_service_capabilities"]);expect(JSON.stringify(observed[0][0])).toContain("이전 질문");expect(JSON.stringify(observed[1][0])).toContain("call-1");expect(persisted).toEqual(["call-1"]);});
 test("supports consecutive turns with different tools and recoverable tool failure",async()=>{const dbInput={...input,connectionId:1};const result=await runAgent(dbInput,{client:client([{type:"tool_calls",calls:[{id:"bad",name:"missing_tool",arguments:"{}"}]},{type:"tool_calls",calls:[{id:"good",name:"get_service_capabilities",arguments:"{}"}]},{type:"final",value:{answer:"완료",sql:null,warnings:[]}}])});expect(result.toolsUsed).toEqual([expect.objectContaining({name:"missing_tool",ok:false}),expect.objectContaining({name:"get_service_capabilities",ok:true})]);});
 test("requests a tool-free final answer when iteration limit is reached",async()=>{const limits={maxIterations:1,maxToolCalls:10,maxConsecutiveSameTool:3,requestTimeoutMs:10000,toolTimeoutMs:100,maxToolResultCharacters:1000,maxUserMessageCharacters:5000,maxPreviousMessages:8};const result=await runAgent(input,{limits,client:client([{type:"tool_calls",calls:[{id:"1",name:"get_service_capabilities",arguments:"{}"}]},{type:"final",value:{answer:"제한 답변",sql:null,warnings:[]}}])});expect(result.metadata.completedReason).toBe("limit_reached");});
 test("rejects invalid model turns and propagates model failures",async()=>{await expect(runAgent(input,{client:client([{type:"tool_calls",calls:[]}])})).rejects.toThrow();const broken:AgentModelClient={async complete(){throw new Error("model down")}};await expect(runAgent(input,{client:broken})).rejects.toThrow("model down");});
 test("searches, describes and relates schema before a SQL draft",async()=>{const turns:AgentModelTurn[]=[{type:"tool_calls",calls:[{id:"s",name:"search_schema",arguments:'{"query":"orders"}'}]},{type:"tool_calls",calls:[{id:"d1",name:"describe_table",arguments:'{"tableName":"orders"}'},{id:"d2",name:"describe_table",arguments:'{"tableName":"items"}'}]},{type:"tool_calls",calls:[{id:"r",name:"find_table_relationships",arguments:'{"tableName":"orders"}'}]},{type:"final",value:{answer:"초안",sql:"SELECT orders.id FROM orders",warnings:[]}}];const result=await runAgent(input,{client:client(turns),registry:schemaRegistry()});expect(result.references).toEqual({schemaVersion:"v000003",tables:["orders","items"],documents:[],businessKnowledge:[],github:{repository:null,files:[]},runtime:null,ui:null,toolsUsed:["search_schema","describe_table","find_table_relationships"]});expect(result.warnings).toContain("이 SQL 초안은 실제 DB에서 실행 검증되지 않았습니다.");});
 test("can recover from empty search or missing table with another schema tool",async()=>{const empty=await runAgent(input,{registry:schemaRegistry(true),client:client([{type:"tool_calls",calls:[{id:"s",name:"search_schema",arguments:"{}"}]},{type:"tool_calls",calls:[{id:"g",name:"get_schema_summary",arguments:"{}"}]},{type:"final",value:{answer:"요약",sql:null,warnings:[]}}])});expect(empty.toolsUsed.map(x=>x.name)).toEqual(["search_schema","get_schema_summary"]);const retry=await runAgent(input,{registry:schemaRegistry(),client:client([{type:"tool_calls",calls:[{id:"d",name:"describe_table",arguments:'{"tableName":"missing"}'}]},{type:"tool_calls",calls:[{id:"s",name:"search_schema",arguments:"{}"}]},{type:"final",value:{answer:"재검색",sql:null,warnings:[]}}])});expect(retry.toolsUsed[0].ok).toBe(false);expect(retry.toolsUsed[1].ok).toBe(true);});
 test("searches and reads knowledge while preserving document evidence",async()=>{const definitions:AgentToolDefinition[]=[{name:"search_knowledge_documents",description:"search",inputSchema:{type:"object",properties:{},additionalProperties:true,required:[]},requiresConnection:false,timeoutMs:100,maxResultCharacters:1000,sensitiveKeys:[],async execute(){return {matches:[{documentId:"service-guide"}]};}},{name:"read_knowledge_document",description:"read",inputSchema:{type:"object",properties:{},additionalProperties:true,required:[]},requiresConnection:false,timeoutMs:100,maxResultCharacters:1000,sensitiveKeys:[],async execute(){return {documentId:"service-guide",title:"서비스 가이드",version:2,updatedAt:"2026-07-29",status:"active",content:"절차"};}}];const result=await runAgent(input,{registry:new ToolRegistry(definitions),client:client([{type:"tool_calls",calls:[{id:"s",name:"search_knowledge_documents",arguments:"{}"}]},{type:"tool_calls",calls:[{id:"r",name:"read_knowledge_document",arguments:"{}"}]},{type:"final",value:{answer:"문서 답변",sql:null,warnings:[]}}])});expect(result.references.documents).toEqual([{id:"service-guide",title:"서비스 가이드",version:2,updatedAt:"2026-07-29",status:"active"}]);});
 test("preserves the exact business definition version used by the agent",async()=>{const definition:AgentToolDefinition={name:"read_business_knowledge",description:"read",inputSchema:{type:"object",properties:{},additionalProperties:true,required:[]},requiresConnection:false,timeoutMs:100,maxResultCharacters:1000,sensitiveKeys:[],async execute(){return {id:"11111111-1111-4111-8111-111111111111",title:"정상 주문 건수",version:3,type:"metric",conditions:[{ruleType:"exclude",columnName:"status",operator:"eq"}]};}};const result=await runAgent(input,{registry:new ToolRegistry([definition]),client:client([{type:"tool_calls",calls:[{id:"bk",name:"read_business_knowledge",arguments:"{}"}]},{type:"final",value:{answer:"공식 기준",sql:null,warnings:[]}}])});expect(result.references.businessKnowledge).toEqual([{id:"11111111-1111-4111-8111-111111111111",title:"정상 주문 건수",version:3,type:"metric",appliedRules:["exclude: status eq"]}]);});
 test("combines bounded runtime evidence without persisting raw logs",async()=>{const definitions:AgentToolDefinition[]=[{name:"get_runtime_project_context",description:"context",inputSchema:{type:"object",properties:{},additionalProperties:true,required:[]},requiresConnection:false,timeoutMs:100,maxResultCharacters:1000,sensitiveKeys:[],async execute(){return{projectId:"app",projectKey:"query-desk",serverId:"server-1",runtimeType:"bun",expectedPort:3000,checkedAt:"2026-08-02T00:00:00.000Z"};}},{name:"get_deployment_status",description:"deployment",inputSchema:{type:"object",properties:{},additionalProperties:true,required:[]},requiresConnection:false,timeoutMs:100,maxResultCharacters:1000,sensitiveKeys:[],async execute(){return{projectId:"app",status:"succeeded",deployedCommit:"1234567",deploymentId:"deploy-1",checkedAt:"2026-08-02T00:01:00.000Z"};}}];const result=await runAgent(input,{registry:new ToolRegistry(definitions),client:client([{type:"tool_calls",calls:[{id:"c",name:"get_runtime_project_context",arguments:"{}"}]},{type:"tool_calls",calls:[{id:"d",name:"get_deployment_status",arguments:"{}"}]},{type:"final",value:{answer:"운영 상태",sql:null,warnings:[]}}])});expect(result.references.runtime).toEqual({projectId:"app",projectKey:"query-desk",serverId:"server-1",runtimeType:"bun",expectedPort:3000,checkedAt:"2026-08-02T00:01:00.000Z",deploymentStatus:"succeeded",deployedCommit:"1234567",processRunning:null,portListening:null,healthOk:null,deploymentId:"deploy-1"});});
 test("preserves bounded deployed UI evidence without DOM or browser storage",async()=>{const definition:AgentToolDefinition={name:"open_ui_page",description:"open",inputSchema:{type:"object",properties:{},additionalProperties:true,required:[]},requiresConnection:false,timeoutMs:100,maxResultCharacters:2000,sensitiveKeys:[],async execute(){return{uiProjectId:"ui",environment:"production",path:"/admin",pageTitle:"Admin",checkedAt:"2026-08-02T01:00:00.000Z",elements:[{ref:"el_1",role:"button",name:"신규 DB 등록",visible:true,enabled:false}],failedNetworkRequestCount:1,consoleErrorCount:0};}};const result=await runAgent(input,{registry:new ToolRegistry([definition]),client:client([{type:"tool_calls",calls:[{id:"ui",name:"open_ui_page",arguments:"{}"}]},{type:"final",value:{answer:"실제 화면 확인",sql:null,warnings:[]}}])});expect(result.references.ui).toEqual({projectId:"ui",environment:"production",path:"/admin",pageTitle:"Admin",checkedAt:"2026-08-02T01:00:00.000Z",elements:[{role:"button",name:"신규 DB 등록",visible:true,enabled:false}],networkErrorCount:1,consoleErrorCount:0,screenshotAvailable:false,deployedCommit:null,mutationBlocked:false});expect(JSON.stringify(result.references.ui)).not.toContain("ref");});
});
