import { DEFAULT_AGENT_LIMITS } from "./limits";
import type { AgentToolDefinition, ToolContext } from "./types";

const projectId={type:"string",minLength:1,maxLength:100} as const;
const role={type:"string",enum:["application","worker","documentation"]} as const;
const common={requiresConnection:true,timeoutMs:10_000,maxResultCharacters:DEFAULT_AGENT_LIMITS.maxToolResultCharacters,sensitiveKeys:["deploymentPath","reportRoot","deploymentStateFile","environment","password","token","secret","authorization","privateKey"]} as const;
async function project(context:ToolContext,id:string){const {requireRuntimeProject}=await import("@/lib/server/runtime-tools/runtime-project-service");return requireRuntimeProject(id,context.connectionId);}

export const runtimeAgentTools:ReadonlyArray<AgentToolDefinition>=[
 {name:"get_runtime_project_context",description:"현재 DB connection에 명시적으로 연결된 운영 프로젝트, runtime, branch, expected port와 안전한 배포 정보를 확인한다. 경로나 credential은 반환하지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{projectRole:role},required:["projectRole"]},...common,async execute(context,input){const {selectRuntimeProject,publicProjectContext}=await import("@/lib/server/runtime-tools/runtime-project-service");const selected=selectRuntimeProject(input.projectRole as "application",context.connectionId),base=publicProjectContext(selected);if(!selected.deploymentStateFile)return{...base,deployedCommit:null,lastSuccessfulDeploymentAt:null,lastDeploymentStatus:"unknown"};const {getDeploymentStatus}=await import("@/lib/server/runtime-tools/deployment-status-service");const deployment=await getDeploymentStatus(selected);return{...base,deployedCommit:deployment.deployedCommit,lastSuccessfulDeploymentAt:deployment.status==="succeeded"?deployment.finishedAt:null,lastDeploymentStatus:deployment.status};}},
 {name:"get_deployment_status",description:"최근 배포 상태와 요청 commit, 실제 배포 commit, 실패 단계의 안전한 요약을 확인한다. 전체 로그는 반환하지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{projectId},required:["projectId"]},...common,async execute(context,input){const selected=await project(context,String(input.projectId));const {getDeploymentStatus}=await import("@/lib/server/runtime-tools/deployment-status-service");return getDeploymentStatus(selected);}},
 {name:"get_process_status",description:"등록된 배포 경로에 속한 프로젝트 프로세스만 조회하여 실행, PID, 중복, zombie와 runtime 일치 여부를 확인한다. 서버 전체 프로세스를 반환하지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{projectId},required:["projectId"]},...common,async execute(context,input){const selected=await project(context,String(input.projectId));const {getProcessStatus}=await import("@/lib/server/runtime-tools/process-status-service");return getProcessStatus(selected);}},
 {name:"get_port_status",description:"등록된 expected port만 조회하고 listener PID와 프로젝트 PID 일치 여부를 확인한다. 사용자 지정 포트 스캔은 지원하지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{projectId},required:["projectId"]},...common,async execute(context,input){const selected=await project(context,String(input.projectId));const {getPortStatus}=await import("@/lib/server/runtime-tools/port-status-service");return getPortStatus(selected);}},
 {name:"run_project_health_check",description:"등록된 내부 endpoint 또는 외부 HTTPS URL만 제한적으로 확인한다. 임의 URL 입력은 받지 않으며 응답 본문은 짧은 안전 요약만 반환한다.",inputSchema:{type:"object",additionalProperties:false,properties:{projectId,checkType:{type:"string",enum:["internal","external"]}},required:["projectId","checkType"]},...common,async execute(context,input){const selected=await project(context,String(input.projectId));const {runProjectHealthCheck}=await import("@/lib/server/runtime-tools/health-check-service");return runProjectHealthCheck(selected,input.checkType as "internal"|"external");}},
 {name:"get_reverse_proxy_status",description:"등록 프로젝트 도메인의 외부 health와 expected upstream port 메타데이터를 비교한다. proxy 설정 원문이나 인증서는 읽지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{projectId},required:["projectId"]},...common,async execute(context,input){const selected=await project(context,String(input.projectId));const {getReverseProxyStatus}=await import("@/lib/server/runtime-tools/health-check-service");return getReverseProxyStatus(selected);}},
 {name:"get_deployment_report",description:"등록 report root에서 projectId와 deploymentId가 일치하는 선택 section만 읽고 secret을 마스킹한다. 파일 경로 입력은 받지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{projectId,deploymentId:{type:"string",minLength:1,maxLength:100},section:{type:"string",enum:["summary","failure","stdout","stderr"]},maxLines:{type:"integer",minimum:1,maximum:200}},required:["projectId","deploymentId","section","maxLines"]},...common,async execute(context,input){const selected=await project(context,String(input.projectId));const {getDeploymentReport}=await import("@/lib/server/runtime-tools/deployment-report-service");return getDeploymentReport(selected,String(input.deploymentId),input.section as "summary"|"failure"|"stdout"|"stderr",Number(input.maxLines));}},
 {name:"compare_deployed_commit_with_repository",description:"실제 배포 state의 commit과 연결 GitHub repository의 허용 ref 최신 commit을 비교한다. 차이는 의도적 고정 배포 가능성과 함께 설명한다.",inputSchema:{type:"object",additionalProperties:false,properties:{projectId,ref:{type:"string",minLength:1,maxLength:100}},required:["projectId","ref"]},...common,async execute(context,input){const selected=await project(context,String(input.projectId));const {compareDeployedCommitWithRepository}=await import("@/lib/server/runtime-tools/deployed-commit-service");return compareDeployedCommitWithRepository(selected,String(input.ref));}},
 {name:"get_runtime_capabilities",description:"현재 연결 프로젝트에서 지원되는 상태 조회 능력과 지원하지 않는 shell, restart, deploy 기능을 확인한다.",inputSchema:{type:"object",additionalProperties:false,properties:{projectRole:role},required:["projectRole"]},...common,async execute(context,input){const {selectRuntimeProject}=await import("@/lib/server/runtime-tools/runtime-project-service");const {getRuntimeCapabilities}=await import("@/lib/server/runtime-tools/runtime-capabilities-service");return getRuntimeCapabilities(selectRuntimeProject(input.projectRole as "application",context.connectionId));}},
];
