import type { AgentToolDefinition } from "./types";
import { DEFAULT_AGENT_LIMITS } from "./limits";
import { validateReadonlySql } from "@/lib/server/sql-tools/readonly-sql-validator";
import { auditReadonlySql } from "@/lib/server/sql-tools/sql-audit";
const sqlSchema={type:"object",additionalProperties:false,properties:{sql:{type:"string",minLength:1,maxLength:100000}},required:["sql"]} as const;
const executeSchema={type:"object",additionalProperties:false,properties:{sql:{type:"string",minLength:1,maxLength:100000},maxRows:{type:"integer",minimum:1,maximum:500}},required:["sql"]} as const;
const common={requiresConnection:true,timeoutMs:15_000,maxResultCharacters:DEFAULT_AGENT_LIMITS.maxToolResultCharacters,sensitiveKeys:["password","encryptedPassword","credential","token","secret"]} as const;
export const sqlAgentTools:ReadonlyArray<AgentToolDefinition>=[
 {name:"validate_readonly_sql",description:"SQL 작성 후 반드시 먼저 호출한다. 최신 선택 DB 스키마로 단일 읽기 전용 SELECT, 객체·컬럼, 위험 함수, system schema, JOIN 및 LIMIT 정책을 검증하며 실패 내용을 보고 SQL을 수정해야 한다.",inputSchema:sqlSchema,...common,async execute(context,input){const sql=String(input.sql);const result=await validateReadonlySql(sql,context.connection!);auditReadonlySql({userId:context.userId,conversationId:context.conversationId,connectionId:context.connectionId!,sql,referencedTables:result.referencedTables,validationSucceeded:result.valid,validationErrorCodes:result.errors.map(e=>e.code),executed:false,blockedReason:result.errors[0]?.code});return result;}},
 {name:"explain_readonly_sql",description:"validate_readonly_sql 성공 후 성능 위험이 예상될 때만 호출한다. 다시 검증한 뒤 MySQL EXPLAIN을 수행하고 full scan, index, filesort, 임시 테이블을 요약한다.",inputSchema:sqlSchema,...common,async execute(context,input){const {explainReadonlySql}=await import("@/lib/server/sql-tools/readonly-sql-explain");return explainReadonlySql(String(input.sql),context.connection!);}},
 {name:"execute_readonly_sql",description:"실제 데이터가 필요하고 사용자가 화면에서 실행을 승인한 경우에만 사용한다. 내부에서 SQL을 반드시 재검증하고 timeout, 행·크기 제한 및 민감정보 마스킹을 적용한다. 승인 없이는 실행하지 않는다.",inputSchema:executeSchema,...common,async execute(context,input){if(!context.executionApproved)return {success:false,error:{code:"SQL_CONNECTION_ACCESS_DENIED",message:"자동 실행은 비활성화되어 있습니다. 검증된 SQL을 화면의 실행 버튼으로 승인해 주세요.",retryable:false},executed:false};const {executeReadonlySql}=await import("@/lib/server/sql-tools/readonly-sql-executor");const sql=String(input.sql),result=await executeReadonlySql(sql,context.connection!,typeof input.maxRows==="number"?input.maxRows:undefined);auditReadonlySql({userId:context.userId,conversationId:context.conversationId,connectionId:context.connectionId!,sql,referencedTables:result.referencedTables,validationSucceeded:true,validationErrorCodes:[],executed:true,executionSucceeded:true,durationMs:result.durationMs,rowCount:result.rowCount,truncated:result.truncated});return result;}}
];
