import { describe, expect, test } from "bun:test";
import { ToolRegistry } from "./tool-registry";
import { executeToolCall } from "./tool-executor";
import type { AgentToolDefinition, ToolContext } from "./types";
import { SchemaToolError } from "@/lib/server/schema-tools/types";
const context:ToolContext={userId:"u",conversationId:"c",connectionId:null,connection:null,securityActor:{userId:"u",organizationId:"org",roles:["security_admin"],active:true,authenticatedAt:Math.floor(Date.now()/1000)}};
const definition=(overrides:Partial<AgentToolDefinition>={}):AgentToolDefinition=>({name:"sample",description:"test",inputSchema:{type:"object",additionalProperties:false,properties:{value:{type:"string"}},required:["value"]},requiresConnection:false,timeoutMs:100,maxResultCharacters:1000,sensitiveKeys:["password"],security:{resourceType:"service",action:"read",riskLevel:"low",auditLevel:"basic",classification:"internal"},async execute(_context,input){return {value:input.value,password:"secret"}},...overrides});
describe("executeToolCall",()=>{
 test("executes valid input and redacts sensitive values",async()=>{const result=await executeToolCall(new ToolRegistry([definition()]),{id:"1",name:"sample",arguments:'{"value":"ok"}'},context);expect(result.ok).toBe(true);if(result.ok)expect(result.data).toEqual({value:"ok",password:"[REDACTED]"});});
 test("rejects invalid input and unknown tools",async()=>{expect((await executeToolCall(new ToolRegistry([definition()]),{id:"1",name:"sample",arguments:"{}"},context)).ok).toBe(false);const missing=await executeToolCall(new ToolRegistry([]),{id:"1",name:"missing",arguments:"{}"},context);expect(missing.ok).toBe(false);});
 test("requires a selected connection",async()=>{const result=await executeToolCall(new ToolRegistry([definition({requiresConnection:true})]),{id:"1",name:"sample",arguments:'{"value":"ok"}'},context);expect(result.ok).toBe(false);if(!result.ok)expect(result.error.code).toBe("CONNECTION_REQUIRED");});
 test("converts exceptions and truncates oversized results",async()=>{const failed=await executeToolCall(new ToolRegistry([definition({async execute(){throw new Error("private")}})]),{id:"1",name:"sample",arguments:'{"value":"ok"}'},context);expect(failed.ok).toBe(false);if(!failed.ok)expect(failed.error.message).not.toContain("private");const large=await executeToolCall(new ToolRegistry([definition({maxResultCharacters:10,async execute(){return {value:"x".repeat(50)}}})]),{id:"2",name:"sample",arguments:'{"value":"ok"}'},context);expect(large.ok&&large.meta.truncated).toBe(true);});
 test("preserves safe schema error codes and retry metadata",async()=>{const result=await executeToolCall(new ToolRegistry([definition({async execute(){throw new SchemaToolError("TABLE_NOT_FOUND","테이블 없음",true,{candidates:["nearby"]});}})]),{id:"1",name:"sample",arguments:'{"value":"x"}'},context);expect(result).toMatchObject({ok:false,error:{code:"TABLE_NOT_FOUND",retryable:true,details:{candidates:["nearby"]}}});});
 test("denies before invoking a handler when policy does not allow the actor",async()=>{let called=false;const restricted=definition({security:{resourceType:"security_policy",action:"manage_permission",riskLevel:"high",auditLevel:"detailed",classification:"restricted"},async execute(){called=true;return{};}}),denied=await executeToolCall(new ToolRegistry([restricted]),{id:"deny",name:"sample",arguments:'{"value":"x"}'},{...context,securityActor:{...context.securityActor!,roles:["user"]}});expect(denied).toMatchObject({ok:false,error:{code:"ACTION_NOT_ALLOWED"}});expect(called).toBe(false);});
});
