import { DEFAULT_AGENT_LIMITS } from "./limits";
import type { AgentToolDefinition,ToolContext } from "./types";
const projectId={type:"string",minLength:1,maxLength:100} as const,environment={type:"string",enum:["local","development","staging","production"]} as const,path={type:"string",minLength:1,maxLength:500} as const,elementRef={type:"string",pattern:"^el_[A-Za-z0-9_-]+$",minLength:4,maxLength:104} as const;
const common={requiresConnection:true,timeoutMs:15_000,maxResultCharacters:DEFAULT_AGENT_LIMITS.maxToolResultCharacters,sensitiveKeys:["cookie","cookies","token","password","credential","authorization","authProfileRef","storage","headers","requestBody","responseBody","selector","xpath"]} as const;
async function project(context:ToolContext,id:string){const {requireUiProject}=await import("@/lib/server/ui-tools/ui-project-service");return requireUiProject(id,context.connectionId);}
const contextOf=(context:ToolContext)=>({userId:context.userId,conversationId:context.conversationId});
export const uiAgentTools:ReadonlyArray<AgentToolDefinition>=[
 {name:"get_ui_project_context",description:"실제 배포 화면을 확인하기 전에 현재 DB connection과 environment에 연결된 UI 프로젝트, 안전한 host와 browser 기능을 확인한다. credential과 storage는 반환하지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{environment},required:["environment"]},...common,async execute(context,input){const {selectUiProject,publicUiProject}=await import("@/lib/server/ui-tools/ui-project-service");const {isBrowserBackendConfigured}=await import("@/lib/server/ui-tools/browser-client");const selected=selectUiProject(input.environment as "production",context.connectionId),base=publicUiProject(selected,isBrowserBackendConfigured());let deployedCommit:null|string=null;const {requireRuntimeProject}=await import("@/lib/server/runtime-tools/runtime-project-service");const runtime=requireRuntimeProject(selected.runtimeProjectId,context.connectionId);if(runtime.deploymentStateFile){const {getDeploymentStatus}=await import("@/lib/server/runtime-tools/deployment-status-service");deployedCommit=(await getDeploymentStatus(runtime)).deployedCommit;}return{...base,deployedCommit,lastHealthStatus:null};}},
 {name:"open_ui_page",description:"등록 base URL에 허용된 상대 path를 열고 title, heading, text, 요소 수와 network/console 오류 수를 확인한다. 외부 redirect와 mutation 요청은 차단한다.",inputSchema:{type:"object",additionalProperties:false,properties:{uiProjectId:projectId,path,waitUntil:{type:"string",enum:["domcontentloaded","load"]}},required:["uiProjectId","path","waitUntil"]},...common,async execute(context,input){const selected=await project(context,String(input.uiProjectId));const {openUiPage}=await import("@/lib/server/ui-tools/browser-inspection-service");return openUiPage(contextOf(context),selected,String(input.path),input.waitUntil as "domcontentloaded");}},
 {name:"inspect_ui_page",description:"현재 page의 접근성 중심 heading, landmark, text, alert와 visible interactive element를 제한된 수로 읽는다. DOM, selector, password 및 hidden input은 반환하지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{uiProjectId:projectId,scope:{type:"string",enum:["main","page","dialog"]},includeText:{type:"boolean"},includeInteractiveElements:{type:"boolean"},maxElements:{type:"integer",minimum:1,maximum:200}},required:["uiProjectId","scope","includeText","includeInteractiveElements","maxElements"]},...common,async execute(context,input){const selected=await project(context,String(input.uiProjectId));const {inspectUiPage}=await import("@/lib/server/ui-tools/browser-inspection-service");return inspectUiPage(contextOf(context),selected,input.scope as "main",Boolean(input.includeText),Boolean(input.includeInteractiveElements),Number(input.maxElements));}},
 {name:"inspect_ui_element",description:"현재 session inspection에서 발급된 안전한 elementRef로 visible, enabled, label, tooltip, href와 action 분류를 확인한다. selector나 password 값은 다루지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{uiProjectId:projectId,elementRef},required:["uiProjectId","elementRef"]},...common,async execute(context,input){const selected=await project(context,String(input.uiProjectId));const {inspectUiElement}=await import("@/lib/server/ui-tools/browser-inspection-service");return inspectUiElement(contextOf(context),selected,String(input.elementRef));}},
 {name:"click_ui_element",description:"dialog, tab, accordion, pagination, 상세보기와 내부 navigation처럼 backend가 read_only로 분류한 요소만 제한적으로 클릭한다. 저장·등록·삭제·로그아웃 등은 차단한다.",inputSchema:{type:"object",additionalProperties:false,properties:{uiProjectId:projectId,elementRef,expectedAction:{type:"string",enum:["open_dialog","switch_tab","toggle_accordion","paginate","view_detail","navigate","open_dropdown","show_help"]}},required:["uiProjectId","elementRef","expectedAction"]},...common,async execute(context,input){const selected=await project(context,String(input.uiProjectId));const {clickUiElement}=await import("@/lib/server/ui-tools/browser-interaction-service");return clickUiElement(contextOf(context),selected,String(input.elementRef),String(input.expectedAction));}},
 {name:"navigate_ui_route",description:"현재 UI 프로젝트의 allowlist 내부 route로만 이동한다. API, logout, download, 외부 host와 destructive query는 차단한다.",inputSchema:{type:"object",additionalProperties:false,properties:{uiProjectId:projectId,path},required:["uiProjectId","path"]},...common,async execute(context,input){const selected=await project(context,String(input.uiProjectId));const {navigateUiRoute}=await import("@/lib/server/ui-tools/browser-interaction-service");return navigateUiRoute(contextOf(context),selected,String(input.path));}},
 {name:"get_ui_network_summary",description:"현재 session의 same-origin network metadata만 요약한다. header와 body는 반환하지 않으며 mutation method는 경고하고 browser에서 차단한다.",inputSchema:{type:"object",additionalProperties:false,properties:{uiProjectId:projectId},required:["uiProjectId"]},...common,async execute(context,input){const selected=await project(context,String(input.uiProjectId));const {getUiNetworkSummary}=await import("@/lib/server/ui-tools/browser-diagnostics-service");return getUiNetworkSummary(contextOf(context),selected);}},
 {name:"get_ui_console_summary",description:"현재 page의 error와 warning만 secret 제거 후 제한적으로 요약한다. 일반 log, 전체 stack과 외부 source를 신뢰 가능한 application source로 표시하지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{uiProjectId:projectId},required:["uiProjectId"]},...common,async execute(context,input){const selected=await project(context,String(input.uiProjectId));const {getUiConsoleSummary}=await import("@/lib/server/ui-tools/browser-diagnostics-service");return getUiConsoleSummary(contextOf(context),selected);}},
 {name:"capture_ui_screenshot",description:"프로젝트 정책이 허용할 때 민감정보와 password 영역을 반드시 마스킹한 screenshot artifact를 생성한다. 내부 경로나 이미지 원문은 반환하지 않는다.",inputSchema:{type:"object",additionalProperties:false,properties:{uiProjectId:projectId,target:{type:"string",enum:["viewport","full_page","element"]},elementRef},required:["uiProjectId","target"]},...common,async execute(context,input){const selected=await project(context,String(input.uiProjectId));const {captureUiScreenshot}=await import("@/lib/server/ui-tools/browser-screenshot-service");return captureUiScreenshot(contextOf(context),selected,input.target as "viewport",typeof input.elementRef==="string"?input.elementRef:undefined);}},
 {name:"get_ui_capabilities",description:"현재 environment에서 실제 사용 가능한 page, inspection, safe click, diagnostics와 screenshot 기능 및 항상 차단되는 form submit, mutation, JavaScript, external navigation을 확인한다.",inputSchema:{type:"object",additionalProperties:false,properties:{environment},required:["environment"]},...common,async execute(context,input){const {selectUiProject}=await import("@/lib/server/ui-tools/ui-project-service");const {isBrowserBackendConfigured}=await import("@/lib/server/ui-tools/browser-client");const {uiInteractionCapabilities}=await import("@/lib/server/ui-tools/ui-action-policy");return uiInteractionCapabilities(selectUiProject(input.environment as "production",context.connectionId),isBrowserBackendConfigured());}},
];
