import { describe, expect, test } from "bun:test";
import { validateKnowledgeInput } from "./business-knowledge-policy";
import { validateAgainstSchema } from "./business-knowledge-validator";
import { rankBusinessKnowledge } from "./business-knowledge-ranking";
import type { BusinessKnowledgeEntry, BusinessKnowledgeInput } from "./business-knowledge-types";
import type { SchemaBundle, TableSchema } from "@/lib/server/schema/types";
import type { TargetConnection } from "@/lib/server/db/target-connections";

const base: BusinessKnowledgeInput = { connectionId: 1, type: "metric", key: "metric.order-count", title: "주문 건수", description: "주문 헤더의 주문 건수를 계산합니다.", status: "draft", priority: 100, source: "운영팀 확인", confidence: "verified", aliases: ["주문 수"], targets: [{ targetType: "table", tableName: "orders" }], metric: { baseTable: "orders", dateColumn: "created_at", aggregationType: "count_distinct", distinctKey: "id", timezone: "Asia/Seoul", nullPolicy: "exclude" }, conditions: [{ ruleType: "exclude", columnName: "status", operator: "eq", value: "cancelled", valueType: "string", groupNo: 0, sequence: 0 }], tags: ["주문"], cautions: [] };
const connection = { id: 1, connectionKey: "sales", displayName: "Sales", host: "localhost", port: 3306, databaseName: "sales", username: "reader", encryptedPassword: "x", active: true, createdAt: new Date(), checkedAt: null, connectionStatus: "healthy" } satisfies TargetConnection;
const columns = ["id", "created_at", "status", "phone"].map((name, index) => ({ ordinalPosition:index+1,name,dataType:name==="created_at"?"datetime":"varchar",columnType:"varchar(20)",characterMaximumLength:20,numericPrecision:null,numericScale:null,datetimePrecision:null,nullable:true,defaultValue:null,extra:"",generated:false,generationExpression:null,characterSet:null,collation:null,comment:"",primaryKey:name==="id",uniqueIndex:false,indexed:name==="id",foreignKey:false,referencedTable:null,referencedColumn:null }));
const table = { name:"orders",type:"BASE TABLE",comment:"",engine:"InnoDB",characterSet:null,collation:null,estimatedRows:1,createdAt:null,updatedAt:null,columns,primaryKey:["id"],foreignKeys:[],indexes:[],view:null } satisfies TableSchema;
const bundle = { manifest:{formatVersion:1,connectionId:1,connectionKey:"sales",displayName:"Sales",dbType:"mysql",databaseName:"sales",generatedAt:new Date(0).toISOString(),tableCount:1,viewCount:0,tables:[{name:"orders",type:"BASE TABLE",comment:"",columnCount:columns.length,primaryKey:["id"],foreignKeyCount:0,indexCount:0,file:"orders.json"}]},relationships:{formatVersion:1,generatedAt:new Date(0).toISOString(),relationships:[]},tables:[{formatVersion:1,databaseName:"sales",table}] } satisfies SchemaBundle;

describe("business knowledge policy", () => {
  test("accepts structured metric and rejects SQL-like system targets", () => { expect(validateKnowledgeInput(base)).toMatchObject({ key:"metric.order-count",type:"metric" }); expect(() => validateKnowledgeInput({ ...base, targets:[{targetType:"table",tableName:"mysql.user"}] })).toThrow(); });
  test("rejects invalid rule operators and reversed periods", () => { expect(() => validateKnowledgeInput({ ...base, conditions:[{...base.conditions[0],operator:"raw sql"}] })).toThrow(); expect(() => validateKnowledgeInput({ ...base,effectiveFrom:"2026-02-01",effectiveTo:"2026-01-01" })).toThrow(); });
});
describe("schema validation", () => {
  test("validates metric tables, date, distinct and rule columns", async () => { expect(await validateAgainstSchema(base,connection,bundle)).toMatchObject({valid:true,schemaVersion:"test-version"}); });
  test("returns concrete missing table and column errors", async () => { const missingTable=await validateAgainstSchema({...base,metric:{...base.metric!,baseTable:"missing"}},connection,bundle);expect(missingTable.errors.map(x=>x.code)).toContain("BUSINESS_KNOWLEDGE_TABLE_NOT_FOUND");const missingColumn=await validateAgainstSchema({...base,metric:{...base.metric!,dateColumn:"missing_at"}},connection,bundle);expect(missingColumn.errors.map(x=>x.code)).toContain("BUSINESS_KNOWLEDGE_COLUMN_NOT_FOUND"); });
  test("does not allow global definitions to carry DB rules", async () => { const result=await validateAgainstSchema({...base,connectionId:null},null,bundle);expect(result.valid).toBeFalse();expect(result.errors[0].code).toBe("BUSINESS_KNOWLEDGE_INVALID_TARGET"); });
});
test("search ranks aliases and target objects while respecting type filters",()=>{const entry:BusinessKnowledgeEntry={...base,id:"11111111-1111-4111-8111-111111111111",version:2,schemaVersion:"v1",validationStatus:"valid",validationErrors:[],lastValidatedAt:null,createdBy:"admin",updatedBy:"admin",createdAt:new Date(0).toISOString(),updatedAt:new Date(0).toISOString()};expect(rankBusinessKnowledge([entry],"주문 수",["metric"],10)[0].entry.id).toBe(entry.id);expect(rankBusinessKnowledge([entry],"주문 수",["term"],10)).toEqual([]);expect(rankBusinessKnowledge([entry],"존재하지 않는 표현",undefined,10)).toEqual([]);});
