import type { ForeignKeySchema, SchemaManifestTable, TableSchemaDocument } from "@/lib/server/schema/types";
import type { LoadedSchemaContext } from "./types";
import { SchemaToolError } from "./types";
import { searchSchemaBundle } from "./search-service";

const relationCount=(context:LoadedSchemaContext,name:string)=>context.bundle.relationships.relationships.filter(r=>r.sourceTable===name||r.targetTable===name).length;
const summaryObject=(context:LoadedSchemaContext,entry:SchemaManifestTable)=>({name:entry.name,objectType:entry.type==="VIEW"?"view":"table",comment:entry.comment,columnCount:entry.columnCount,relationshipCount:relationCount(context,entry.name),hasPrimaryKey:entry.primaryKey.length>0,primaryColumns:entry.primaryKey.slice(0,3)});
export function getSchemaSummary(context:LoadedSchemaContext){const manifest=context.bundle.manifest,totalColumns=manifest.tables.reduce((sum,item)=>sum+item.columnCount,0);const mainTables=[...manifest.tables].sort((a,b)=>relationCount(context,b.name)-relationCount(context,a.name)||b.columnCount-a.columnCount||a.name.localeCompare(b.name)).slice(0,20).map(entry=>({...summaryObject(context,entry),keyColumns:context.bundle.tables.find(d=>d.table.name===entry.name)?.table.columns.filter(c=>c.primaryKey||c.foreignKey||c.indexed).slice(0,5).map(c=>c.name)??[]}));return {status:"success",displayName:manifest.displayName,connectionKey:manifest.connectionKey,schemaVersion:context.versionLabel,schemaHash:context.schemaHash,generatedAt:context.generatedAt,tableCount:manifest.tableCount,viewCount:manifest.viewCount,totalColumnCount:totalColumns,relationshipCount:context.bundle.relationships.relationships.length,mainObjects:mainTables,truncated:manifest.tables.length>mainTables.length};}
export function getSchemaVersion(context:LoadedSchemaContext){const manifest=context.bundle.manifest;return {status:"success",schemaVersion:context.versionLabel,schemaHash:context.schemaHash,generatedAt:context.generatedAt,objectCount:manifest.tableCount+manifest.viewCount,tableCount:manifest.tableCount,viewCount:manifest.viewCount,previousVersionExists:context.previousVersionExists,databaseSynchronization:"not_verified",lastGenerationError:null};}
export function listSchemaObjects(context:LoadedSchemaContext,input:{objectType:"table"|"view"|"all";page:number;pageSize:number}){if(!["table","view","all"].includes(input.objectType)||!Number.isSafeInteger(input.page)||input.page<1||!Number.isSafeInteger(input.pageSize)||input.pageSize<1||input.pageSize>100)throw new SchemaToolError("INVALID_SCHEMA_QUERY","객체 유형 또는 페이지 조건이 올바르지 않습니다.",true);const filtered=context.bundle.manifest.tables.filter(entry=>input.objectType==="all"||(input.objectType==="table"?entry.type==="BASE TABLE":entry.type==="VIEW"));const start=(input.page-1)*input.pageSize;return {schemaVersion:context.versionLabel,objectType:input.objectType,objects:filtered.slice(start,start+input.pageSize).map(entry=>summaryObject(context,entry)),page:input.page,pageSize:input.pageSize,total:filtered.length,totalPages:Math.ceil(filtered.length/input.pageSize),hasNext:start+input.pageSize<filtered.length};}
function exactTable(context:LoadedSchemaContext,tableName:string):TableSchemaDocument|null{if(typeof tableName!=="string"||!tableName.trim()||tableName.length>128||/[\\/\0]/.test(tableName)||tableName.includes(".."))throw new SchemaToolError("INVALID_SCHEMA_QUERY","테이블명이 올바르지 않습니다.",true);const exact=context.bundle.tables.find(item=>item.table.name===tableName);if(exact)return exact;const folded=context.bundle.tables.filter(item=>item.table.name.toLocaleLowerCase()===tableName.toLocaleLowerCase());return folded.length===1?folded[0]:null;}
export function describeTable(context:LoadedSchemaContext,tableName:string){const document=exactTable(context,tableName);if(!document){const candidates=searchSchemaBundle(context.bundle,tableName,5).map(item=>item.tableName);throw new SchemaToolError("TABLE_NOT_FOUND","요청한 테이블을 현재 스키마에서 찾을 수 없습니다.",true,{candidates});}const table=document.table,incoming=context.bundle.relationships.relationships.filter(r=>r.targetTable===table.name);return {schemaVersion:context.versionLabel,table:{name:table.name,comment:table.comment,objectType:table.type==="VIEW"?"view":"table",engine:table.engine,estimatedRows:table.estimatedRows,primaryKey:table.primaryKey,columns:table.columns.slice(0,300).map(column=>({name:column.name,dataType:column.dataType,columnType:column.columnType,nullable:column.nullable,defaultValue:column.defaultValue,primaryKey:column.primaryKey,autoIncrement:/auto_increment/i.test(column.extra),unsigned:/\bunsigned\b/i.test(column.columnType),generated:column.generated,indexed:column.indexed,unique:column.uniqueIndex,comment:column.comment})),columnsTruncated:table.columns.length>300,indexes:table.indexes,foreignKeys:table.foreignKeys,outgoingRelationships:relationships(context,table.name,"outgoing"),incomingRelationships:incoming.map(r=>relationResult(r,table.name))}};}
const relationResult=(relation:ForeignKeySchema,base:string)=>({baseTable:base,relatedTable:relation.sourceTable===base?relation.targetTable:relation.sourceTable,baseColumns:relation.sourceTable===base?relation.sourceColumns:relation.targetColumns,relatedColumns:relation.sourceTable===base?relation.targetColumns:relation.sourceColumns,direction:relation.sourceTable===base?"outgoing":"incoming",constraintName:relation.constraintName,source:"database_foreign_key",explicit:true,inferred:false,confidence:1,updateRule:relation.updateRule,deleteRule:relation.deleteRule});
export function relationships(context:LoadedSchemaContext,tableName:string,direction:"outgoing"|"incoming"|"both"){const document=exactTable(context,tableName);if(!document)throw new SchemaToolError("TABLE_NOT_FOUND","관계를 조회할 테이블을 현재 스키마에서 찾을 수 없습니다.",true,{candidates:searchSchemaBundle(context.bundle,tableName,5).map(x=>x.tableName)});const values=context.bundle.relationships.relationships.filter(r=>direction==="both"?r.sourceTable===document.table.name||r.targetTable===document.table.name:direction==="outgoing"?r.sourceTable===document.table.name:r.targetTable===document.table.name);return values.map(r=>relationResult(r,document.table.name));}
export function findTableRelationships(context:LoadedSchemaContext,tableName:string,direction:"outgoing"|"incoming"|"both",depth:number){if(!["outgoing","incoming","both"].includes(direction)||depth!==1)throw new SchemaToolError("INVALID_SCHEMA_QUERY","관계 방향은 outgoing, incoming, both이며 현재 depth는 1만 지원합니다.",true);return {schemaVersion:context.versionLabel,baseTable:tableName,direction,depth,relationships:relationships(context,tableName,direction),relationshipSource:"explicit_foreign_keys_only",inferredRelationshipsIncluded:false};}
