import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { loadSchemaContext } from "./context-service";
import { normalizeSchemaSearch, searchSchemaBundle } from "./search-service";
import { describeTable, findTableRelationships, getSchemaSummary, getSchemaVersion, listSchemaObjects } from "./schema-service";
import { calculateSchemaHash } from "@/lib/server/schema/schema-hash";
import { publishCurrentSchema } from "@/lib/server/schema/schema-current";
import { tableFileName, writeSchemaFiles, writeVersionedSchemaFiles } from "@/lib/server/schema/write-schema-files";
import type { SchemaBundle, TableSchemaDocument } from "@/lib/server/schema/types";
import type { TargetConnection } from "@/lib/server/db/target-connections";

let root="";afterEach(async()=>{if(root)await rm(root,{recursive:true,force:true});root="";});
const connection:TargetConnection={id:7,connectionKey:"demo",displayName:"데모 DB",host:"secret",port:3306,databaseName:"demo",username:"secret",encryptedPassword:"secret",active:true,createdAt:new Date(0),checkedAt:null,connectionStatus:"healthy"};
function document(name:string,type:"BASE TABLE"|"VIEW",comment:string,columns:Array<[string,string]>):TableSchemaDocument{return {formatVersion:1,databaseName:"demo",table:{name,type,comment,engine:type==="VIEW"?null:"InnoDB",characterSet:"utf8mb4",collation:null,estimatedRows:10,createdAt:null,updatedAt:null,columns:columns.map(([column,columnComment],index)=>({ordinalPosition:index+1,name:column,dataType:"int",columnType:index===0?"int unsigned":"int",characterMaximumLength:null,numericPrecision:10,numericScale:0,datetimePrecision:null,nullable:index>0,defaultValue:null,extra:index===0?"auto_increment":"",generated:false,generationExpression:null,characterSet:null,collation:null,comment:columnComment,primaryKey:index===0,uniqueIndex:index===0,indexed:true,foreignKey:false,referencedTable:null,referencedColumn:null})),primaryKey:[columns[0][0]],foreignKeys:[],indexes:[{name:`idx_${columns[0][0]}`,primary:true,unique:true,type:"BTREE",columns:[{ordinalPosition:1,name:columns[0][0],prefixLength:null,direction:"ASC"}]}],view:type==="VIEW"?{checkOption:null,updatable:false,securityType:"DEFINER",definition:null,definitionAccessible:false}:null}};}
function fixture():SchemaBundle{const tables=[document("sales_orders","BASE TABLE","주문 헤더",[["order_id","주문 식별자"],["client_id","고객 식별자"]]),document("customer_accounts","BASE TABLE","고객 계정",[["client_id","고객 키"],["phone_number","전화번호"]]),document("monthly_sales","VIEW","월별 매출 뷰",[["month_key","월"]])];const relation={constraintName:"fk_order_customer",sourceTable:"sales_orders",sourceColumns:["client_id"],targetTable:"customer_accounts",targetColumns:["client_id"],updateRule:"RESTRICT",deleteRule:"RESTRICT"};return {manifest:{formatVersion:1,connectionId:7,connectionKey:"demo",displayName:"데모 DB",dbType:"mysql",databaseName:"demo",generatedAt:"2026-07-29T00:00:00.000Z",tableCount:2,viewCount:1,tables:tables.map(d=>({name:d.table.name,type:d.table.type,comment:d.table.comment,columnCount:d.table.columns.length,primaryKey:d.table.primaryKey,foreignKeyCount:d.table.name==="sales_orders"?1:0,indexCount:d.table.indexes.length,file:`tables/${tableFileName(d.table.name)}`}))},relationships:{formatVersion:1,generatedAt:"2026-07-29T00:00:00.000Z",relationships:[relation]},tables:tables.map(d=>d.table.name==="sales_orders"?{...d,table:{...d.table,foreignKeys:[relation]}}:d)};}
async function versioned(){root=await mkdtemp(path.join(tmpdir(),"schema-tools-"));const schemas=path.join(root,"schemas"),bundle=fixture();await writeVersionedSchemaFiles(bundle,2,schemas);await publishCurrentSchema({formatVersion:1,connectionId:7,connectionKey:"demo",latestVersion:2,path:"versions/v000002",generatedAt:bundle.manifest.generatedAt,schemaHash:calculateSchemaHash(bundle)},schemas);return loadSchemaContext(connection,root);}

describe("schema context",()=>{
 test("loads current version without exposing internal paths",async()=>{const context=await versioned();expect(context.versionLabel).toBe("v000002");expect(JSON.stringify(getSchemaSummary(context))).not.toContain(root);});
 test("loads legacy flat schemas",async()=>{root=await mkdtemp(path.join(tmpdir(),"schema-flat-"));await writeSchemaFiles(fixture(),path.join(root,"schemas"));expect((await loadSchemaContext(connection,root)).versionLabel).toBe("legacy-flat");});
 test("distinguishes missing, corrupt and missing version files",async()=>{root=await mkdtemp(path.join(tmpdir(),"schema-errors-"));await expect(loadSchemaContext(connection,root)).rejects.toMatchObject({code:"SCHEMA_NOT_GENERATED"});await mkdir(path.join(root,"schemas","demo"),{recursive:true});await writeFile(path.join(root,"schemas","demo","current.json"),"{");await expect(loadSchemaContext(connection,root)).rejects.toMatchObject({code:"SCHEMA_FILE_CORRUPTED"});await writeFile(path.join(root,"schemas","demo","current.json"),JSON.stringify({formatVersion:1,connectionId:7,connectionKey:"demo",latestVersion:9,path:"versions/v000009",generatedAt:new Date().toISOString(),schemaHash:"a".repeat(64)}));await expect(loadSchemaContext(connection,root)).rejects.toMatchObject({code:"SCHEMA_VERSION_NOT_FOUND"});});
});
describe("schema services",()=>{
 test("summarizes counts and versions with bounded objects",async()=>{const context=await versioned(),summary=getSchemaSummary(context),version=getSchemaVersion(context);expect(summary).toMatchObject({tableCount:2,viewCount:1,totalColumnCount:5,relationshipCount:1});expect(summary.mainObjects.length).toBeLessThanOrEqual(20);expect(version.databaseSynchronization).toBe("not_verified");});
 test("lists tables and views with pagination and validates limits",async()=>{const context=await versioned();expect(listSchemaObjects(context,{objectType:"table",page:1,pageSize:1})).toMatchObject({total:2,hasNext:true});expect(listSchemaObjects(context,{objectType:"view",page:1,pageSize:10}).objects[0].name).toBe("monthly_sales");expect(()=>listSchemaObjects(context,{objectType:"all",page:1,pageSize:101})).toThrow();});
 test("searches normalized names and all comment levels in score order",()=>{const bundle=fixture();expect(normalizeSchemaSearch("Sales_ORDERS")).toBe("sales orders");expect(normalizeSchemaSearch("SalesOrders")).toBe("sales orders");expect(searchSchemaBundle(bundle,"sales orders",10)[0].tableName).toBe("sales_orders");expect(searchSchemaBundle(bundle,"주문",10)[0].matchedBy).toContain("table_comment");expect(searchSchemaBundle(bundle,"전화번호",10)[0].matchedBy).toContain("column_comment");expect(searchSchemaBundle(bundle,"없는업무",10)).toEqual([]);expect(()=>searchSchemaBundle(bundle,"x",21)).toThrow();});
 test("describes real tables, returns candidates and blocks traversal names",async()=>{const context=await versioned(),result=describeTable(context,"sales_orders");expect(result.table.columns[0]).toMatchObject({name:"order_id",autoIncrement:true,unsigned:true});expect(result.table.indexes).toHaveLength(1);expect(()=>describeTable(context,"sales_order")).toThrow();try{describeTable(context,"sales_order");}catch(error){expect(error).toMatchObject({code:"TABLE_NOT_FOUND",retryable:true});expect((error as {details:{candidates:string[]}}).details.candidates).toContain("sales_orders");}expect(()=>describeTable(context,"../secret")).toThrow();});
 test("returns explicit outgoing, incoming and both relationships only",async()=>{const context=await versioned();const outgoing=findTableRelationships(context,"sales_orders","outgoing",1),incoming=findTableRelationships(context,"customer_accounts","incoming",1),both=findTableRelationships(context,"sales_orders","both",1);expect(outgoing.relationships[0]).toMatchObject({relatedTable:"customer_accounts",explicit:true,inferred:false,source:"database_foreign_key"});expect(incoming.relationships[0].direction).toBe("incoming");expect(both.inferredRelationshipsIncluded).toBe(false);expect(()=>findTableRelationships(context,"sales_orders","both",2)).toThrow();});
});
