import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

type Source = "environment" | "git" | "unknown";

const SHA_PATTERN = /^[0-9a-f]{40,64}$/i;
const runGit = (args: string[]) => {
  const result = Bun.spawnSync(["git", ...args], { stdout: "pipe", stderr: "ignore" });
  return result.exitCode === 0 ? result.stdout.toString().trim() : null;
};
const gitExit = (args: string[]) => Bun.spawnSync(["git", ...args], { stdout: "ignore", stderr: "ignore" }).exitCode;

const environmentSha = process.env.BUILD_COMMIT_SHA?.trim() ?? "";
const gitSha = environmentSha ? null : runGit(["rev-parse", "HEAD"]);
const candidate = environmentSha || gitSha || "";
const commitSha = SHA_PATTERN.test(candidate) ? candidate.toLowerCase() : "unknown";
const source: Source = commitSha === "unknown" ? "unknown" : environmentSha ? "environment" : "git";
const dirty = source === "git"
  ? gitExit(["diff", "--quiet"]) === 1 || gitExit(["diff", "--cached", "--quiet"]) === 1
  : null;

const buildInfo = {
  commitSha,
  commitShort: commitSha === "unknown" ? "unknown" : commitSha.slice(0, 7),
  buildTime: new Date().toISOString(),
  source,
  dirty,
  requiredFilesManifestVersion: 1,
} as const;

const output = resolve(process.env.BUILD_INFO_OUTPUT || "src/generated/build-info.ts");
await mkdir(dirname(output), { recursive: true });
await writeFile(output, `// Generated by scripts/generate-build-info.ts. Do not edit.\nexport const BUILD_INFO = ${JSON.stringify(buildInfo, null, 2)} as const;\n`, "utf8");
console.log(`Build metadata generated: ${buildInfo.commitShort} (${buildInfo.source})`);
