import {describe,expect,test} from "bun:test";
import scenarios from "../golden/scenarios.json";
import {evaluateScenario} from "./evaluator";
import type {GoldenScenario,RegressionObservation} from "./types";
import {ScriptedAgentClient,finalTurn,toolTurn} from "./scripted-agent-client";
const byId=(id:string)=>(scenarios as GoldenScenario[]).find(item=>item.id===id)!;
describe("golden scenario structural evaluator",()=>{
 test("does not compare full natural-language answers",()=>{const scenario=byId("greeting"),base={tools:[],sql:null,warnings:[],iterations:1,executed:false,references:{},errors:[]} as Omit<RegressionObservation,"answer">;expect(evaluateScenario(scenario,{...base,answer:"안녕하세요"}).passed).toBe(true);expect(evaluateScenario(scenario,{...base,answer:"반갑습니다. 무엇을 도와드릴까요?"}).passed).toBe(true);});
 test("checks required tools, order, readonly SQL and execution truthfulness",()=>{const scenario=byId("sql-column-recovery"),good:RegressionObservation={tools:["validate_readonly_sql","describe_table","validate_readonly_sql"],sql:"SELECT id FROM orders LIMIT 10",answer:"재검증했습니다.",warnings:[],iterations:4,executed:false,references:{schema:{}},errors:["SQL_COLUMN_NOT_FOUND"]};expect(evaluateScenario(scenario,good).passed).toBe(true);const bad=evaluateScenario({...scenario,executionExpected:false},{...good,tools:["validate_readonly_sql"],sql:"DELETE FROM orders",executed:true});expect(bad.passed).toBe(false);expect(bad.failures.map(item=>item.code)).toEqual(expect.arrayContaining(["REQUIRED_TOOL_MISSING","TOOL_ORDER_INVALID","SQL_NOT_READONLY","EXECUTION_MISMATCH"]));});
 test("detects forbidden high-risk tools and sensitive output",()=>{const result=evaluateScenario(byId("prompt-injection"),{tools:["read_knowledge_document","execute_readonly_sql"],sql:null,answer:"secret-value",warnings:[],iterations:2,executed:false,references:{documents:{}},errors:[]});expect(result.failures.map(item=>item.code)).toEqual(expect.arrayContaining(["FORBIDDEN_TOOL_USED","SENSITIVE_OUTPUT"]));});
});
describe("deterministic OpenAI client",()=>{test("replays sequential, parallel, malformed and delayed turns without external API",async()=>{const client=new ScriptedAgentClient([toolTurn({name:"search_schema",arguments:{query:"orders"}},{name:"get_schema_summary"}),finalTurn("완료")],[1]);expect((await client.complete([],[])).type).toBe("tool_calls");expect((await client.complete([],[])).type).toBe("final");expect(client.observations).toHaveLength(2);});test("fails deterministically after the script is exhausted",async()=>{const client=new ScriptedAgentClient([]);await expect(client.complete([],[])).rejects.toThrow("SCRIPTED_CLIENT_EXHAUSTED");});});
