import type { TargetConnection } from "@/lib/server/db/target-connections";
import { inspectOpenAiConfig } from "@/lib/server/openai/config";
import { runAgent } from "@/lib/server/agent/orchestrator";
import type { AgentToolCall, ToolResult } from "@/lib/server/agent/types";
import { buildConversationContext } from "./conversation-context-service";
import { acquireConversation, addMessage, archiveConversation, createConversation, finishRun, getWorkingState, recordToolCall, releaseConversation, requireConversation, startRun, updateWorkingState } from "./conversation-repository";
import { EMPTY_WORKING_STATE, type WorkingState } from "./conversation-types";
import { refreshConversationSummary } from "./conversation-summary-service";

export async function processConversationQuestion(input:{userId:string;connection:TargetConnection;conversationId?:string;requestId:string;prompt:string}){
 const model=inspectOpenAiConfig().model,conversation=input.conversationId?await requireConversation(input.conversationId,input.userId,input.connection.id):await createConversation(input.userId,input.connection.id,input.prompt,model);await acquireConversation(conversation.id,input.userId,input.connection.id);let runId:string|null=null;
 try{const context=await buildConversationContext(conversation,input.connection);const user=await addMessage({conversationId:conversation.id,role:"user",content:input.prompt,status:"success",requestId:input.requestId,model});runId=await startRun(conversation.id,user.id,input.connection.id);const toolEvents:Array<{call:AgentToolCall;result:ToolResult}>=[];const generated=await runAgent({userId:input.userId,connectionId:input.connection.id,conversationId:conversation.id,userMessage:input.prompt,connection:input.connection,previousMessages:context.messages},{onToolResult:async(call,result)=>{toolEvents.push({call,result});await recordToolCall(runId!,call,result);}});const assistantMetadata={sql:generated.sql,references:generated.references,warnings:generated.warnings,toolsUsed:generated.references.toolsUsed};const assistant=await addMessage({conversationId:conversation.id,role:"assistant",content:generated.answer,status:"success",parentMessageId:user.id,model,metadata:assistantMetadata});const current=(await getWorkingState(conversation.id))??EMPTY_WORKING_STATE;const validated=toolEvents.findLast(event=>event.call.name==="validate_readonly_sql"&&event.result.ok&&(event.result.data as {valid?:boolean})?.valid);const executed=toolEvents.findLast(event=>event.call.name==="execute_readonly_sql"&&event.result.ok&&(event.result.data as {success?:boolean})?.success);const next:Omit<WorkingState,"version">={intent:input.prompt.slice(0,500),answerSummary:generated.answer.slice(0,1000),lastSql:generated.sql,validatedSql:validated&&validated.result.ok?String((validated.result.data as {normalizedSql?:string}).normalizedSql??generated.sql):null,executedSql:executed&&executed.result.ok?String((executed.result.data as {executedSql?:string}).executedSql??generated.sql):null,resultSummary:executed&&executed.result.ok?sanitizeExecutionSummary(executed.result.data):null,tables:generated.references.tables.slice(0,50),columns:extractColumns(validated&&validated.result.ok?validated.result.data:undefined),documents:generated.references.documents.map(x=>x.id).slice(0,50),schemaVersion:generated.references.schemaVersion??current.schemaVersion,filters:{},period:null,aggregation:null,executed:Boolean(executed),warnings:generated.warnings.slice(0,20),assumptions:[]};await updateWorkingState(conversation.id,current.version,next);await finishRun(runId,{status:"success",assistantMessageId:assistant.id,iterations:generated.metadata.iterations,toolCalls:toolEvents.length,reason:generated.metadata.completedReason,schemaVersion:next.schemaVersion,executed:next.executed});await refreshConversationSummary({...conversation,messageCount:conversation.messageCount+2}).catch(()=>undefined);return {generated,conversationId:conversation.id,messageId:assistant.id,isNew:!input.conversationId,contextMessagesUsed:context.contextMessagesUsed,summaryUsed:context.summaryUsed,workingStateUpdated:true,contextNotice:context.notice};
 }catch(error){if(runId)await finishRun(runId,{status:"failed",errorCode:error&&typeof error==="object"&&"code" in error?String(error.code):"AGENT_FAILED"}).catch(()=>undefined);throw error;}finally{await releaseConversation(conversation.id).catch(()=>undefined);}
}
const extractColumns=(data:unknown)=>data&&typeof data==="object"&&Array.isArray((data as {referencedColumns?:unknown}).referencedColumns)?(data as {referencedColumns:string[]}).referencedColumns.slice(0,100):[];
function sanitizeExecutionSummary(data:unknown){if(!data||typeof data!=="object")return null;const item=data as Record<string,unknown>;return {rowCount:Number(item.rowCount??0),truncated:Boolean(item.truncated),durationMs:Number(item.durationMs??0),maskedColumns:Array.isArray(item.maskedColumns)?item.maskedColumns:[],note:"전체 결과 행은 대화 이력에 저장하지 않았습니다."};}
export async function resetConversation(userId:string,conversationId:string){await archiveConversation(conversationId,userId);}
export async function recordConversationExecution(input:{userId:string;conversationId:string;connectionId:number;sql:string;result:{rowCount:number;truncated:boolean;durationMs:number;maskedColumns?:ReadonlyArray<string>}}){const conversation=await requireConversation(input.conversationId,input.userId,input.connectionId);await acquireConversation(conversation.id,input.userId,input.connectionId);try{const current=(await getWorkingState(conversation.id))??EMPTY_WORKING_STATE;await updateWorkingState(conversation.id,current.version,{...current,lastSql:input.sql,validatedSql:input.sql,executedSql:input.sql,resultSummary:{rowCount:input.result.rowCount,truncated:input.result.truncated,durationMs:input.result.durationMs,maskedColumns:input.result.maskedColumns??[],note:"전체 결과 행은 저장하지 않았습니다."},executed:true});}finally{await releaseConversation(conversation.id);}}
