import type { AgentMessage } from "@/lib/server/agent/types";

export type ConversationStatus = "active" | "archived" | "deleted";
export type ConversationErrorCode = "CONVERSATION_NOT_FOUND"|"CONVERSATION_ACCESS_DENIED"|"CONVERSATION_CLOSED"|"CONVERSATION_CONNECTION_MISMATCH"|"CONVERSATION_CONTEXT_LOAD_FAILED"|"CONVERSATION_MESSAGE_SAVE_FAILED"|"CONVERSATION_RUN_SAVE_FAILED"|"CONVERSATION_STATE_CONFLICT"|"CONVERSATION_REQUEST_DUPLICATED"|"CONVERSATION_CONTEXT_TOO_LARGE"|"CONVERSATION_SUMMARY_FAILED"|"CONVERSATION_STATE_UPDATE_FAILED"|"CONVERSATION_RESET_FAILED";
export class ConversationError extends Error { constructor(public readonly code:ConversationErrorCode,message:string,public readonly retryable=false){super(message);} }
export type Conversation = Readonly<{id:string;userId:string;title:string;connectionId:number;status:ConversationStatus;createdAt:string;lastActivityAt:string;schemaVersion:string|null;model:string|null;stateVersion:number;summary:string|null;messageCount:number;lastQuestion:string|null;hasSql:boolean;executed:boolean}>;
export type StoredMessage = Readonly<{id:string;conversationId:string;role:"user"|"assistant"|"tool";content:string;sequence:number;status:"pending"|"success"|"failed";requestId:string|null;parentMessageId:string|null;model:string|null;metadata:Record<string,unknown>|null;createdAt:string}>;
export type WorkingState = Readonly<{intent:string|null;answerSummary:string|null;lastSql:string|null;validatedSql:string|null;executedSql:string|null;resultSummary:Record<string,unknown>|null;tables:ReadonlyArray<string>;columns:ReadonlyArray<string>;documents:ReadonlyArray<string>;schemaVersion:string|null;filters:Record<string,string>;period:string|null;aggregation:string|null;executed:boolean;warnings:ReadonlyArray<string>;assumptions:ReadonlyArray<string>;version:number}>;
export type ConversationContext = Readonly<{messages:ReadonlyArray<AgentMessage>;workingState:WorkingState|null;summaryUsed:boolean;contextMessagesUsed:number;schemaChanged:boolean;notice:string|null}>;
export const EMPTY_WORKING_STATE:WorkingState=Object.freeze({intent:null,answerSummary:null,lastSql:null,validatedSql:null,executedSql:null,resultSummary:null,tables:[],columns:[],documents:[],schemaVersion:null,filters:{},period:null,aggregation:null,executed:false,warnings:[],assumptions:[],version:0});
